//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "patient")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique)]
    pub user_id: Uuid,
    pub date_of_birth: Date,
    pub emergency_contact_name: String,
    pub emergency_contact_phone: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub medical_conditions: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub current_medications: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::appointment::Entity")]
    Appointment,
    #[sea_orm(has_many = "super::medical_record::Entity")]
    MedicalRecord,
    #[sea_orm(has_many = "super::prescription::Entity")]
    Prescription,
    #[sea_orm(has_many = "super::test_result::Entity")]
    TestResult,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::UserId",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Users,
}

impl Related<super::appointment::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Appointment.def()
    }
}

impl Related<super::medical_record::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MedicalRecord.def()
    }
}

impl Related<super::prescription::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Prescription.def()
    }
}

impl Related<super::test_result::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TestResult.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
