//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

pub use super::doctor::Entity as Doctor;
pub use super::patient::Entity as Patient;
pub use super::roles::Entity as Roles;
pub use super::users::Entity as Users;
