//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

pub use super::appointment::Entity as Appointment;
pub use super::doctor::Entity as Doctor;
pub use super::medical_record::Entity as MedicalRecord;
pub use super::patient::Entity as Patient;
pub use super::prescription::Entity as Prescription;
pub use super::roles::Entity as Roles;
pub use super::test_result::Entity as TestResult;
pub use super::users::Entity as Users;
