//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "doctor_specialization"
)]
pub enum DoctorSpecialization {
    #[sea_orm(string_value = "general")]
    General,
    #[sea_orm(string_value = "cardiology")]
    Cardiology,
    #[sea_orm(string_value = "pediatrics")]
    Pediatrics,
    #[sea_orm(string_value = "orthopedics")]
    Orthopedics,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "role")]
pub enum Role {
    #[sea_orm(string_value = "admin")]
    Admin,
    #[sea_orm(string_value = "user")]
    User,
    #[sea_orm(string_value = "none")]
    None,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "usertype")]
pub enum Usertype {
    #[sea_orm(string_value = "admin")]
    Admin,
    #[sea_orm(string_value = "patient")]
    Patient,
    #[sea_orm(string_value = "doctor")]
    Doctor,
}
