services:
  rust-server:
    container_name: rust-server
    image: ghcr.io/mattjoe480/chime/api-server:latest
    ports:
      - "8080:8080"
      - "50051:50051"
    environment:
      - RUST_LOG=info
      - MONGO_URI=mongodb://127.0.0.1:27017  # Use localhost as MongoDB URI
      - REDIS_URI=redis://127.0.0.1:6379  # Use localhost as Redis URI
      - GRPC_URL=0.0.0.0:50051  # Bind GRPC server to all interfaces
      - JWT_ACCESS_TOKEN_TTL=1
      - JWT_TTL=1
      - JWT_TOKEN_TOKEN_TTL=720
      - JWT_KEY=testingkey
      - JWT_REFRESH_KEY=testingrefreshkey

    deploy:
      update_config:
        order: start-first
    depends_on:
      - redis
      - mongo

  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 30s         # Run health check every 30 seconds
      timeout: 10s          # Wait 10 seconds for the command to complete
      start_period: 10s     # Give 10 seconds for the container to start before health checks begin
      retries: 4            # Retry the health check 5 times before marking as unhealthy
    ports:
      - "6379:6379"  # Expose Redis port 6379 to the host

  mongo:
    image: mongo:latest
    container_name: mongo
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 30s         # Run health check every 30 seconds
      retries: 3            # Retry 3 times before marking as unhealthy
      timeout: 10s          # Wait 10 seconds for the command to complete
      start_period: 10s     # Give 10 seconds for the container to start before health checks begin

    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=example
    ports:
      - "27017:27017"
    restart: unless-stopped
volumes:
  mongodb_data:
    driver: local