services:
  rust_server:
    container_name: rust-server
#    build:
#      cache_from:
#        - ghcr.io/mattjoe480/chime/api-server:latest
#      context: ./
#      dockerfile: Dockerfile
    image: ghcr.io/mattjoe480/chime/api-server:latest
    environment:
      - LOG_LEVEL=DEBUG
      - GRPC_URL=0.0.0.0:50051
      - JWT_ACCESS_TOKEN_TTL=1
      - JWT_KEY=YAWbbw1XsbTkHBtgqDfypjg23IE0DLfoVqH4KB
      - JWT_REFRESH_KEY=A6nffudKLpEXM5Z4gzrOodMgewYjDqhGSxeMxy
      - JWT_TOKEN_TOKEN_TTL=720
      - JWT_TTL=1
      - REDIS_PASSWORD=vIHdT6wcUpfmI029m9w1KhPCJgQrkDdnP7TvSFmyDOx7bcM6W4W5EXcgjuBQEz0Q
      - POSTGRES_PASSWORD=75k2K2YODUrkfpYX4nzWcQZRyDdUvK27YK7DivYUpFiudEMNCKUNxwkO8S05ZAcd
      - POSTGRES_URI=178.16.138.165:5432/postgres
      - POSTGRES_USER=postgres
      - REDIS_URI=redis://:vIHdT6wcUpfmI029m9w1KhPCJgQrkDdnP7TvSFmyDOx7bcM6W4W5EXcgjuBQEz0Q@178.16.138.165
      - SCYLLA_URL=178.16.138.165:9042
      - SCYLLA_BROADCAST_ADDRESS=178.16.138.165
      - SCYLLA_CLUSTER_NAME=scyllacluster1
      - SCYLLA_LISTEN_ADDRESS=178.16.138.165
      - SCYLLA_SEEDS=178.16.138.165
      - SERVER_URL=0.0.0.0:8000
    expose:
      - 8000
      - 50051
    networks:
      - app_network
    deploy:
      update_config:
        order: start-first
    restart: on-failure

  nginx:
    image: "nginx:alpine"
    container_name: "nginx"
    networks:
      - app_network
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Nginx configuration file
    ports:
      - "8001:8080"
      - "8002:8001"

networks:
  app_network:
    driver: bridge