worker_processes 1;


events {

    worker_connections 1024;
}

http {

    log_format  lol  ‘Api $remote_addr – $remote_user [$time_local] “$request” ‘

                          ‘$status $body_bytes_sent “$http_referer” ‘

                          ‘”$http_user_agent”‘;
    log_format  hehe  ‘Grpc $remote_addr – $remote_user [$time_local] “$request” ‘

                          ‘$status $body_bytes_sent “$http_referer” ‘

                          ‘”$http_user_agent”‘;
    server {
            listen 8080 http2;  # HTTP/2 support is required for gRPC

            # gRPC endpoint for gRPC traffic (using gRPC over HTTP/2)
            server_name grpc.localhost;

            # This location block will handle the gRPC traffic
            location / {
                grpc_pass grpc://rust_server:50051;  # gRPC backend service (replace with your actual service)
                error_page 502 = /error502grpc;
            }

            # Error handling for gRPC
            location = /error502grpc {
                internal;
                default_type application/grpc;
                add_header grpc-status 14;
                return 204;
            }
        }

        # HTTP endpoint for HTTP traffic (using HTTP/1.1)
        server {
            listen 8081;
            server_name api.localhost;
            location / {
                proxy_pass http://rust_server:8001;  # HTTP backend service (replace with your actual service)
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
            }
        }
}

