// This file is @generated by prost-build.
/// Message structure with optional text, audio, and files
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Message {
    /// Current status of the message
    #[prost(enumeration = "MessageStatus", tag = "1")]
    pub status: i32,
    /// Time the message was sent
    #[prost(message, optional, tag = "2")]
    pub send_time: ::core::option::Option<::prost_types::Timestamp>,
    /// Time the message was delivered
    #[prost(message, optional, tag = "3")]
    pub delivered_time: ::core::option::Option<::prost_types::Timestamp>,
    /// Time the message was read
    #[prost(message, optional, tag = "4")]
    pub read_time: ::core::option::Option<::prost_types::Timestamp>,
    /// Unique ID for the message (different from sender_uid)
    #[prost(string, tag = "13")]
    pub uid: ::prost::alloc::string::String,
    #[prost(oneof = "message::Data", tags = "5, 6, 7, 8, 9, 10, 11")]
    pub data: ::core::option::Option<message::Data>,
}
/// Nested message and enum types in `Message`.
pub mod message {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Data {
        /// Text message
        #[prost(string, tag = "5")]
        Text(::prost::alloc::string::String),
        /// Audio message (raw audio data)
        #[prost(bytes, tag = "6")]
        Audio(::prost::alloc::vec::Vec<u8>),
        /// Video message (raw video data)
        #[prost(bytes, tag = "7")]
        Video(::prost::alloc::vec::Vec<u8>),
        /// Document file (e.g., PDF, Word)
        #[prost(bytes, tag = "8")]
        Document(::prost::alloc::vec::Vec<u8>),
        /// Image file (e.g., JPEG, PNG)
        #[prost(bytes, tag = "9")]
        Image(::prost::alloc::vec::Vec<u8>),
        /// Generic file
        #[prost(bytes, tag = "10")]
        File(::prost::alloc::vec::Vec<u8>),
        /// Link
        #[prost(string, tag = "11")]
        Url(::prost::alloc::string::String),
    }
}
/// MessageEvent structure for sending/receiving messages
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MessageEvent {
    /// The action (e.g., send, receive, edit)
    #[prost(enumeration = "MessageCommand", tag = "1")]
    pub command: i32,
    /// Unique ID for the message (different from sender_uid)
    #[prost(string, tag = "2")]
    pub event_uid: ::prost::alloc::string::String,
    /// Sender's user ID
    #[prost(string, tag = "3")]
    pub sender_uid: ::prost::alloc::string::String,
    /// List of recipient user IDs
    #[prost(string, repeated, tag = "4")]
    pub dst_uids: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// The message content
    #[prost(message, optional, tag = "5")]
    pub message: ::core::option::Option<Message>,
}
/// Typing event (optional for "user typing" notifications)
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TypingEvent {
    /// Sender's user ID
    #[prost(string, tag = "1")]
    pub sender_uid: ::prost::alloc::string::String,
    /// List of recipient user IDs
    #[prost(string, repeated, tag = "2")]
    pub dst_uids: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// Whether the user is typing
    #[prost(bool, tag = "3")]
    pub is_typing: bool,
}
/// User status event (optional for online/offline status)
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UserStatusEvent {
    /// User's unique ID
    #[prost(string, tag = "1")]
    pub user_uid: ::prost::alloc::string::String,
    /// Whether the user is online
    #[prost(bool, tag = "2")]
    pub is_online: bool,
}
/// Message status update (optional for message read/delivered status change)
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MessageStatusUpdate {
    /// Unique message ID
    #[prost(string, tag = "1")]
    pub message_uid: ::prost::alloc::string::String,
    /// New status (e.g., "delivered")
    #[prost(enumeration = "MessageStatus", tag = "2")]
    pub new_status: i32,
}
/// Key exchange message for secure communication
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct KeyExchange {
    /// Sender's user ID
    #[prost(string, tag = "1")]
    pub sender_uid: ::prost::alloc::string::String,
    /// Sender's identity public key (Curve25519)
    #[prost(bytes = "vec", tag = "2")]
    pub identity_key: ::prost::alloc::vec::Vec<u8>,
    /// Sender's signed pre-key (Curve25519)
    #[prost(bytes = "vec", tag = "3")]
    pub signed_pre_key: ::prost::alloc::vec::Vec<u8>,
    /// Signature of the signed pre-key
    #[prost(bytes = "vec", tag = "4")]
    pub signed_pre_key_signature: ::prost::alloc::vec::Vec<u8>,
    /// Sender's one-time pre-key (Curve25519)
    #[prost(bytes = "vec", tag = "5")]
    pub one_time_pre_key: ::prost::alloc::vec::Vec<u8>,
    /// Signature of the one-time pre-key
    #[prost(bytes = "vec", tag = "6")]
    pub one_time_pre_key_signature: ::prost::alloc::vec::Vec<u8>,
    /// Ephemeral public key (Curve25519)
    #[prost(bytes = "vec", tag = "7")]
    pub ephemeral_key: ::prost::alloc::vec::Vec<u8>,
    /// Optional encrypted data (for session data)
    #[prost(bytes = "vec", tag = "8")]
    pub encrypted_data: ::prost::alloc::vec::Vec<u8>,
    /// Digital signature of the sender to verify the authenticity
    #[prost(string, tag = "9")]
    pub signature: ::prost::alloc::string::String,
}
/// SuccessEvent to indicate successful operation (e.g., message sent, key exchange successful)
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SuccessEvent {
    /// Unique ID for the event (to track the success)
    #[prost(string, tag = "1")]
    pub event_uid: ::prost::alloc::string::String,
    /// Code indicating the success type (e.g., MESSAGE_SENT)
    #[prost(enumeration = "SuccessCode", tag = "2")]
    pub success_code: i32,
    /// Optional description providing additional context (e.g., "Message Sent")
    #[prost(string, tag = "3")]
    pub description: ::prost::alloc::string::String,
}
/// Wrapper for different types of events (oneof for multiple event types)
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Events {
    #[prost(oneof = "events::Event", tags = "1, 2, 3, 4, 5, 6")]
    pub event: ::core::option::Option<events::Event>,
}
/// Nested message and enum types in `Events`.
pub mod events {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Event {
        /// New message event
        #[prost(message, tag = "1")]
        MessageEvent(super::MessageEvent),
        /// Typing status event
        #[prost(message, tag = "2")]
        TypingEvent(super::TypingEvent),
        /// User status event
        #[prost(message, tag = "3")]
        UserStatusEvent(super::UserStatusEvent),
        /// Message status update event
        #[prost(message, tag = "4")]
        StatusUpdate(super::MessageStatusUpdate),
        /// Key exchange event
        #[prost(message, tag = "5")]
        KeyExchangeEvent(super::KeyExchange),
        /// Success event
        #[prost(message, tag = "6")]
        SuccessEvent(super::SuccessEvent),
    }
}
/// Enum for success codes
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum SuccessCode {
    /// Default unknown success status
    SuccessUnknown = 0,
    /// Message was successfully sent
    MessageSent = 1,
    /// Key exchange was successfully completed
    KeyExchangeCompleted = 2,
    /// Message was delivered successfully
    MessageDelivered = 3,
    /// Session was successfully established
    SessionEstablished = 4,
}
impl SuccessCode {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::SuccessUnknown => "SUCCESS_UNKNOWN",
            Self::MessageSent => "MESSAGE_SENT",
            Self::KeyExchangeCompleted => "KEY_EXCHANGE_COMPLETED",
            Self::MessageDelivered => "MESSAGE_DELIVERED",
            Self::SessionEstablished => "SESSION_ESTABLISHED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "SUCCESS_UNKNOWN" => Some(Self::SuccessUnknown),
            "MESSAGE_SENT" => Some(Self::MessageSent),
            "KEY_EXCHANGE_COMPLETED" => Some(Self::KeyExchangeCompleted),
            "MESSAGE_DELIVERED" => Some(Self::MessageDelivered),
            "SESSION_ESTABLISHED" => Some(Self::SessionEstablished),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum MessageCommand {
    /// Send a new message
    MessageSend = 0,
    /// Receive a message
    MessageReceive = 1,
    /// Update the timestamp (e.g., resend or reattempt)
    UpdateTimestamp = 2,
    /// Edit the content of an existing message
    EditMessage = 3,
    /// Delete the message from the system
    DeleteMessage = 4,
    /// Forward the message to other users
    ForwardMessage = 5,
    /// Retry sending a message (e.g., after failure)
    RetrySend = 6,
    /// Mark the message as important
    MarkAsImportant = 7,
    /// Archive the message (for storage)
    ArchiveMessage = 8,
    /// Unarchive a previously archived message
    UnarchiveMessage = 9,
    /// Mark the message as spam
    MarkAsSpam = 10,
    /// Mark the message as read (may be used explicitly)
    MarkAsRead = 11,
    /// Mark the message as unread
    MarkAsUnread = 12,
    /// Revoke a message (remove it from recipients' devices)
    RevokeMessage = 13,
    /// Pin the message to the top of a chat or thread
    PinMessage = 14,
    /// Unpin a previously pinned message
    UnpinMessage = 15,
}
impl MessageCommand {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::MessageSend => "MESSAGE_SEND",
            Self::MessageReceive => "MESSAGE_RECEIVE",
            Self::UpdateTimestamp => "UPDATE_TIMESTAMP",
            Self::EditMessage => "EDIT_MESSAGE",
            Self::DeleteMessage => "DELETE_MESSAGE",
            Self::ForwardMessage => "FORWARD_MESSAGE",
            Self::RetrySend => "RETRY_SEND",
            Self::MarkAsImportant => "MARK_AS_IMPORTANT",
            Self::ArchiveMessage => "ARCHIVE_MESSAGE",
            Self::UnarchiveMessage => "UNARCHIVE_MESSAGE",
            Self::MarkAsSpam => "MARK_AS_SPAM",
            Self::MarkAsRead => "MARK_AS_READ",
            Self::MarkAsUnread => "MARK_AS_UNREAD",
            Self::RevokeMessage => "REVOKE_MESSAGE",
            Self::PinMessage => "PIN_MESSAGE",
            Self::UnpinMessage => "UNPIN_MESSAGE",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "MESSAGE_SEND" => Some(Self::MessageSend),
            "MESSAGE_RECEIVE" => Some(Self::MessageReceive),
            "UPDATE_TIMESTAMP" => Some(Self::UpdateTimestamp),
            "EDIT_MESSAGE" => Some(Self::EditMessage),
            "DELETE_MESSAGE" => Some(Self::DeleteMessage),
            "FORWARD_MESSAGE" => Some(Self::ForwardMessage),
            "RETRY_SEND" => Some(Self::RetrySend),
            "MARK_AS_IMPORTANT" => Some(Self::MarkAsImportant),
            "ARCHIVE_MESSAGE" => Some(Self::ArchiveMessage),
            "UNARCHIVE_MESSAGE" => Some(Self::UnarchiveMessage),
            "MARK_AS_SPAM" => Some(Self::MarkAsSpam),
            "MARK_AS_READ" => Some(Self::MarkAsRead),
            "MARK_AS_UNREAD" => Some(Self::MarkAsUnread),
            "REVOKE_MESSAGE" => Some(Self::RevokeMessage),
            "PIN_MESSAGE" => Some(Self::PinMessage),
            "UNPIN_MESSAGE" => Some(Self::UnpinMessage),
            _ => None,
        }
    }
}
/// Enum for message statuses
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum MessageStatus {
    /// Message has been sent but not yet delivered
    Pending = 0,
    /// Message delivered to recipients
    Delivered = 1,
    /// Message read by the recipient
    Read = 2,
    /// Message failed to send or deliver
    Failed = 3,
}
impl MessageStatus {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Pending => "PENDING",
            Self::Delivered => "DELIVERED",
            Self::Read => "READ",
            Self::Failed => "FAILED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "PENDING" => Some(Self::Pending),
            "DELIVERED" => Some(Self::Delivered),
            "READ" => Some(Self::Read),
            "FAILED" => Some(Self::Failed),
            _ => None,
        }
    }
}
/// Generated client implementations.
pub mod chat_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    #[derive(Debug, Clone)]
    pub struct ChatClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl ChatClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> ChatClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::BoxBody>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> ChatClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::BoxBody>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            ChatClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        pub async fn message_service(
            &mut self,
            request: impl tonic::IntoStreamingRequest<Message = super::Events>,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::Events>>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/events.Chat/MessageService",
            );
            let mut req = request.into_streaming_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("events.Chat", "MessageService"));
            self.inner.streaming(req, path, codec).await
        }
    }
}
/// Generated server implementations.
pub mod chat_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with ChatServer.
    #[async_trait]
    pub trait Chat: std::marker::Send + std::marker::Sync + 'static {
        /// Server streaming response type for the MessageService method.
        type MessageServiceStream: tonic::codegen::tokio_stream::Stream<
                Item = std::result::Result<super::Events, tonic::Status>,
            >
            + std::marker::Send
            + 'static;
        async fn message_service(
            &self,
            request: tonic::Request<tonic::Streaming<super::Events>>,
        ) -> std::result::Result<
            tonic::Response<Self::MessageServiceStream>,
            tonic::Status,
        >;
    }
    #[derive(Debug)]
    pub struct ChatServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> ChatServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for ChatServer<T>
    where
        T: Chat,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::BoxBody>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/events.Chat/MessageService" => {
                    #[allow(non_camel_case_types)]
                    struct MessageServiceSvc<T: Chat>(pub Arc<T>);
                    impl<T: Chat> tonic::server::StreamingService<super::Events>
                    for MessageServiceSvc<T> {
                        type Response = super::Events;
                        type ResponseStream = T::MessageServiceStream;
                        type Future = BoxFuture<
                            tonic::Response<Self::ResponseStream>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<tonic::Streaming<super::Events>>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Chat>::message_service(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = MessageServiceSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.streaming(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(empty_body());
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for ChatServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "events.Chat";
    impl<T> tonic::server::NamedService for ChatServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
