// This file is @generated by prost-build.
/// Patient profile information
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PatientProfile {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub user_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub email: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "5")]
    pub date_of_birth: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(string, tag = "6")]
    pub emergency_contact_name: ::prost::alloc::string::String,
    #[prost(string, tag = "7")]
    pub emergency_contact_phone: ::prost::alloc::string::String,
    #[prost(string, tag = "8")]
    pub medical_conditions: ::prost::alloc::string::String,
    #[prost(string, tag = "9")]
    pub current_medications: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "10")]
    pub created_at: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(message, optional, tag = "11")]
    pub updated_at: ::core::option::Option<::prost_types::Timestamp>,
}
/// Medical record entry
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MedicalRecord {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub patient_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub doctor_id: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "4")]
    pub date: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(string, tag = "5")]
    pub diagnosis: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub treatment: ::prost::alloc::string::String,
    #[prost(string, tag = "7")]
    pub notes: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "8")]
    pub created_at: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(message, optional, tag = "9")]
    pub updated_at: ::core::option::Option<::prost_types::Timestamp>,
}
/// Prescription information
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Prescription {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub patient_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub doctor_id: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub medication_name: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub dosage: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub frequency: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "7")]
    pub start_date: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(message, optional, tag = "8")]
    pub end_date: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(string, tag = "9")]
    pub instructions: ::prost::alloc::string::String,
    /// Active, Completed, Cancelled
    #[prost(string, tag = "10")]
    pub status: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "11")]
    pub created_at: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(message, optional, tag = "12")]
    pub updated_at: ::core::option::Option<::prost_types::Timestamp>,
}
/// Test result information
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TestResult {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub patient_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub doctor_id: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub test_name: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "5")]
    pub test_date: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(string, tag = "6")]
    pub results: ::prost::alloc::string::String,
    #[prost(string, tag = "7")]
    pub reference_range: ::prost::alloc::string::String,
    #[prost(string, tag = "8")]
    pub interpretation: ::prost::alloc::string::String,
    /// Pending, Completed, Cancelled
    #[prost(string, tag = "9")]
    pub status: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "10")]
    pub created_at: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(message, optional, tag = "11")]
    pub updated_at: ::core::option::Option<::prost_types::Timestamp>,
}
/// Appointment information
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Appointment {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub patient_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub doctor_id: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "4")]
    pub datetime: ::core::option::Option<::prost_types::Timestamp>,
    /// in minutes
    #[prost(int32, tag = "5")]
    pub duration: i32,
    /// Consultation, Follow-up, Check-up
    #[prost(string, tag = "6")]
    pub r#type: ::prost::alloc::string::String,
    /// Scheduled, Completed, Cancelled
    #[prost(string, tag = "7")]
    pub status: ::prost::alloc::string::String,
    #[prost(string, tag = "8")]
    pub notes: ::prost::alloc::string::String,
    #[prost(string, tag = "9")]
    pub reason: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "10")]
    pub created_at: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(message, optional, tag = "11")]
    pub updated_at: ::core::option::Option<::prost_types::Timestamp>,
}
/// Request/Response messages for services
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetPatientProfileRequest {
    #[prost(string, tag = "1")]
    pub patient_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetPatientProfileResponse {
    #[prost(message, optional, tag = "1")]
    pub profile: ::core::option::Option<PatientProfile>,
    #[prost(enumeration = "super::auth::Status", tag = "2")]
    pub status: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UpdatePatientProfileRequest {
    #[prost(string, tag = "1")]
    pub patient_id: ::prost::alloc::string::String,
    #[prost(string, optional, tag = "2")]
    pub emergency_contact_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "3")]
    pub emergency_contact_phone: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "4")]
    pub medical_conditions: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "5")]
    pub current_medications: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UpdatePatientProfileResponse {
    #[prost(message, optional, tag = "1")]
    pub profile: ::core::option::Option<PatientProfile>,
    #[prost(enumeration = "super::auth::Status", tag = "2")]
    pub status: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListMedicalRecordsRequest {
    #[prost(string, tag = "1")]
    pub patient_id: ::prost::alloc::string::String,
    #[prost(int32, tag = "2")]
    pub page: i32,
    #[prost(int32, tag = "3")]
    pub limit: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListMedicalRecordsResponse {
    #[prost(message, repeated, tag = "1")]
    pub records: ::prost::alloc::vec::Vec<MedicalRecord>,
    #[prost(int32, tag = "2")]
    pub total: i32,
    #[prost(int32, tag = "3")]
    pub page: i32,
    #[prost(int32, tag = "4")]
    pub total_pages: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListPrescriptionsRequest {
    #[prost(string, tag = "1")]
    pub patient_id: ::prost::alloc::string::String,
    #[prost(int32, tag = "2")]
    pub page: i32,
    #[prost(int32, tag = "3")]
    pub limit: i32,
    /// Optional filter by status
    #[prost(string, tag = "4")]
    pub status: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListPrescriptionsResponse {
    #[prost(message, repeated, tag = "1")]
    pub prescriptions: ::prost::alloc::vec::Vec<Prescription>,
    #[prost(int32, tag = "2")]
    pub total: i32,
    #[prost(int32, tag = "3")]
    pub page: i32,
    #[prost(int32, tag = "4")]
    pub total_pages: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListTestResultsRequest {
    #[prost(string, tag = "1")]
    pub patient_id: ::prost::alloc::string::String,
    #[prost(int32, tag = "2")]
    pub page: i32,
    #[prost(int32, tag = "3")]
    pub limit: i32,
    /// Optional filter by status
    #[prost(string, tag = "4")]
    pub status: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListTestResultsResponse {
    #[prost(message, repeated, tag = "1")]
    pub results: ::prost::alloc::vec::Vec<TestResult>,
    #[prost(int32, tag = "2")]
    pub total: i32,
    #[prost(int32, tag = "3")]
    pub page: i32,
    #[prost(int32, tag = "4")]
    pub total_pages: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListAppointmentsRequest {
    #[prost(string, tag = "1")]
    pub patient_id: ::prost::alloc::string::String,
    #[prost(int32, tag = "2")]
    pub page: i32,
    #[prost(int32, tag = "3")]
    pub limit: i32,
    /// Optional filter by status
    #[prost(string, tag = "4")]
    pub status: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "5")]
    pub start_date: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(message, optional, tag = "6")]
    pub end_date: ::core::option::Option<::prost_types::Timestamp>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListAppointmentsResponse {
    #[prost(message, repeated, tag = "1")]
    pub appointments: ::prost::alloc::vec::Vec<Appointment>,
    #[prost(int32, tag = "2")]
    pub total: i32,
    #[prost(int32, tag = "3")]
    pub page: i32,
    #[prost(int32, tag = "4")]
    pub total_pages: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BookAppointmentRequest {
    #[prost(string, tag = "1")]
    pub patient_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub doctor_id: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "3")]
    pub datetime: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(string, tag = "4")]
    pub r#type: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub reason: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BookAppointmentResponse {
    #[prost(message, optional, tag = "1")]
    pub appointment: ::core::option::Option<Appointment>,
    #[prost(enumeration = "super::auth::Status", tag = "2")]
    pub status: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CancelAppointmentRequest {
    #[prost(string, tag = "1")]
    pub appointment_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub reason: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct CancelAppointmentResponse {
    #[prost(enumeration = "super::auth::Status", tag = "1")]
    pub status: i32,
}
/// Generated client implementations.
pub mod patient_service_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    /// Patient service definition
    #[derive(Debug, Clone)]
    pub struct PatientServiceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl PatientServiceClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> PatientServiceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::BoxBody>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> PatientServiceClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::BoxBody>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            PatientServiceClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// Profile management
        pub async fn get_patient_profile(
            &mut self,
            request: impl tonic::IntoRequest<super::GetPatientProfileRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetPatientProfileResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/patient.PatientService/GetPatientProfile",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("patient.PatientService", "GetPatientProfile"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn update_patient_profile(
            &mut self,
            request: impl tonic::IntoRequest<super::UpdatePatientProfileRequest>,
        ) -> std::result::Result<
            tonic::Response<super::UpdatePatientProfileResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/patient.PatientService/UpdatePatientProfile",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("patient.PatientService", "UpdatePatientProfile"),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Medical records
        pub async fn list_medical_records(
            &mut self,
            request: impl tonic::IntoRequest<super::ListMedicalRecordsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ListMedicalRecordsResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/patient.PatientService/ListMedicalRecords",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("patient.PatientService", "ListMedicalRecords"));
            self.inner.unary(req, path, codec).await
        }
        /// Prescriptions
        pub async fn list_prescriptions(
            &mut self,
            request: impl tonic::IntoRequest<super::ListPrescriptionsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ListPrescriptionsResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/patient.PatientService/ListPrescriptions",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("patient.PatientService", "ListPrescriptions"));
            self.inner.unary(req, path, codec).await
        }
        /// Test results
        pub async fn list_test_results(
            &mut self,
            request: impl tonic::IntoRequest<super::ListTestResultsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ListTestResultsResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/patient.PatientService/ListTestResults",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("patient.PatientService", "ListTestResults"));
            self.inner.unary(req, path, codec).await
        }
        /// Appointments
        pub async fn list_appointments(
            &mut self,
            request: impl tonic::IntoRequest<super::ListAppointmentsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ListAppointmentsResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/patient.PatientService/ListAppointments",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("patient.PatientService", "ListAppointments"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn book_appointment(
            &mut self,
            request: impl tonic::IntoRequest<super::BookAppointmentRequest>,
        ) -> std::result::Result<
            tonic::Response<super::BookAppointmentResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/patient.PatientService/BookAppointment",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("patient.PatientService", "BookAppointment"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn cancel_appointment(
            &mut self,
            request: impl tonic::IntoRequest<super::CancelAppointmentRequest>,
        ) -> std::result::Result<
            tonic::Response<super::CancelAppointmentResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/patient.PatientService/CancelAppointment",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("patient.PatientService", "CancelAppointment"));
            self.inner.unary(req, path, codec).await
        }
    }
}
/// Generated server implementations.
pub mod patient_service_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with PatientServiceServer.
    #[async_trait]
    pub trait PatientService: std::marker::Send + std::marker::Sync + 'static {
        /// Profile management
        async fn get_patient_profile(
            &self,
            request: tonic::Request<super::GetPatientProfileRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetPatientProfileResponse>,
            tonic::Status,
        >;
        async fn update_patient_profile(
            &self,
            request: tonic::Request<super::UpdatePatientProfileRequest>,
        ) -> std::result::Result<
            tonic::Response<super::UpdatePatientProfileResponse>,
            tonic::Status,
        >;
        /// Medical records
        async fn list_medical_records(
            &self,
            request: tonic::Request<super::ListMedicalRecordsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ListMedicalRecordsResponse>,
            tonic::Status,
        >;
        /// Prescriptions
        async fn list_prescriptions(
            &self,
            request: tonic::Request<super::ListPrescriptionsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ListPrescriptionsResponse>,
            tonic::Status,
        >;
        /// Test results
        async fn list_test_results(
            &self,
            request: tonic::Request<super::ListTestResultsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ListTestResultsResponse>,
            tonic::Status,
        >;
        /// Appointments
        async fn list_appointments(
            &self,
            request: tonic::Request<super::ListAppointmentsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ListAppointmentsResponse>,
            tonic::Status,
        >;
        async fn book_appointment(
            &self,
            request: tonic::Request<super::BookAppointmentRequest>,
        ) -> std::result::Result<
            tonic::Response<super::BookAppointmentResponse>,
            tonic::Status,
        >;
        async fn cancel_appointment(
            &self,
            request: tonic::Request<super::CancelAppointmentRequest>,
        ) -> std::result::Result<
            tonic::Response<super::CancelAppointmentResponse>,
            tonic::Status,
        >;
    }
    /// Patient service definition
    #[derive(Debug)]
    pub struct PatientServiceServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> PatientServiceServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for PatientServiceServer<T>
    where
        T: PatientService,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::BoxBody>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/patient.PatientService/GetPatientProfile" => {
                    #[allow(non_camel_case_types)]
                    struct GetPatientProfileSvc<T: PatientService>(pub Arc<T>);
                    impl<
                        T: PatientService,
                    > tonic::server::UnaryService<super::GetPatientProfileRequest>
                    for GetPatientProfileSvc<T> {
                        type Response = super::GetPatientProfileResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetPatientProfileRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as PatientService>::get_patient_profile(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetPatientProfileSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/patient.PatientService/UpdatePatientProfile" => {
                    #[allow(non_camel_case_types)]
                    struct UpdatePatientProfileSvc<T: PatientService>(pub Arc<T>);
                    impl<
                        T: PatientService,
                    > tonic::server::UnaryService<super::UpdatePatientProfileRequest>
                    for UpdatePatientProfileSvc<T> {
                        type Response = super::UpdatePatientProfileResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::UpdatePatientProfileRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as PatientService>::update_patient_profile(
                                        &inner,
                                        request,
                                    )
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = UpdatePatientProfileSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/patient.PatientService/ListMedicalRecords" => {
                    #[allow(non_camel_case_types)]
                    struct ListMedicalRecordsSvc<T: PatientService>(pub Arc<T>);
                    impl<
                        T: PatientService,
                    > tonic::server::UnaryService<super::ListMedicalRecordsRequest>
                    for ListMedicalRecordsSvc<T> {
                        type Response = super::ListMedicalRecordsResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::ListMedicalRecordsRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as PatientService>::list_medical_records(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = ListMedicalRecordsSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/patient.PatientService/ListPrescriptions" => {
                    #[allow(non_camel_case_types)]
                    struct ListPrescriptionsSvc<T: PatientService>(pub Arc<T>);
                    impl<
                        T: PatientService,
                    > tonic::server::UnaryService<super::ListPrescriptionsRequest>
                    for ListPrescriptionsSvc<T> {
                        type Response = super::ListPrescriptionsResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::ListPrescriptionsRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as PatientService>::list_prescriptions(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = ListPrescriptionsSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/patient.PatientService/ListTestResults" => {
                    #[allow(non_camel_case_types)]
                    struct ListTestResultsSvc<T: PatientService>(pub Arc<T>);
                    impl<
                        T: PatientService,
                    > tonic::server::UnaryService<super::ListTestResultsRequest>
                    for ListTestResultsSvc<T> {
                        type Response = super::ListTestResultsResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::ListTestResultsRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as PatientService>::list_test_results(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = ListTestResultsSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/patient.PatientService/ListAppointments" => {
                    #[allow(non_camel_case_types)]
                    struct ListAppointmentsSvc<T: PatientService>(pub Arc<T>);
                    impl<
                        T: PatientService,
                    > tonic::server::UnaryService<super::ListAppointmentsRequest>
                    for ListAppointmentsSvc<T> {
                        type Response = super::ListAppointmentsResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::ListAppointmentsRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as PatientService>::list_appointments(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = ListAppointmentsSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/patient.PatientService/BookAppointment" => {
                    #[allow(non_camel_case_types)]
                    struct BookAppointmentSvc<T: PatientService>(pub Arc<T>);
                    impl<
                        T: PatientService,
                    > tonic::server::UnaryService<super::BookAppointmentRequest>
                    for BookAppointmentSvc<T> {
                        type Response = super::BookAppointmentResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::BookAppointmentRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as PatientService>::book_appointment(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = BookAppointmentSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/patient.PatientService/CancelAppointment" => {
                    #[allow(non_camel_case_types)]
                    struct CancelAppointmentSvc<T: PatientService>(pub Arc<T>);
                    impl<
                        T: PatientService,
                    > tonic::server::UnaryService<super::CancelAppointmentRequest>
                    for CancelAppointmentSvc<T> {
                        type Response = super::CancelAppointmentResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::CancelAppointmentRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as PatientService>::cancel_appointment(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = CancelAppointmentSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(empty_body());
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for PatientServiceServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "patient.PatientService";
    impl<T> tonic::server::NamedService for PatientServiceServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
