/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 5.28.3
 * source: auth.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as dependency_1 from "./google/protobuf/timestamp";
import * as pb_1 from "google-protobuf";
import * as grpc_1 from "@grpc/grpc-js";
export namespace auth {
    export enum Status {
        AUTH_SUCCESS = 0,
        AUTH_FAILED = 1,
        INVALID_CREDENTIALS = 2,
        EXPIRED_TOKEN = 3,
        ACCOUNT_LOCKED = 4,
        USER_NOT_FOUND = 5,
        MFA_REQUIRED = 6,
        MFA_FAILED = 7,
        INVALID_TOKEN = 8,
        DUPLICATE_EMAIL = 9,
        WEAK_PASSWORD = 10,
        INVALID_PROVIDER = 11,
        INTERNAL_ERROR = 12,
        INVALID_EMAIL = 13
    }
    export enum AuthProvider {
        GOOGLE = 0,
        FACEBOOK = 1,
        GITHUB = 2
    }
    export class OAuth extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            oauth_token?: string;
            expires_in?: string;
            expires_at?: string;
            providerAccountID?: string;
            provider?: string;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("oauth_token" in data && data.oauth_token != undefined) {
                    this.oauth_token = data.oauth_token;
                }
                if ("expires_in" in data && data.expires_in != undefined) {
                    this.expires_in = data.expires_in;
                }
                if ("expires_at" in data && data.expires_at != undefined) {
                    this.expires_at = data.expires_at;
                }
                if ("providerAccountID" in data && data.providerAccountID != undefined) {
                    this.providerAccountID = data.providerAccountID;
                }
                if ("provider" in data && data.provider != undefined) {
                    this.provider = data.provider;
                }
            }
        }
        get oauth_token() {
            return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
        }
        set oauth_token(value: string) {
            pb_1.Message.setField(this, 1, value);
        }
        get expires_in() {
            return pb_1.Message.getFieldWithDefault(this, 2, "") as string;
        }
        set expires_in(value: string) {
            pb_1.Message.setField(this, 2, value);
        }
        get expires_at() {
            return pb_1.Message.getFieldWithDefault(this, 3, "") as string;
        }
        set expires_at(value: string) {
            pb_1.Message.setField(this, 3, value);
        }
        get providerAccountID() {
            return pb_1.Message.getFieldWithDefault(this, 4, "") as string;
        }
        set providerAccountID(value: string) {
            pb_1.Message.setField(this, 4, value);
        }
        get provider() {
            return pb_1.Message.getFieldWithDefault(this, 5, "") as string;
        }
        set provider(value: string) {
            pb_1.Message.setField(this, 5, value);
        }
        static fromObject(data: {
            oauth_token?: string;
            expires_in?: string;
            expires_at?: string;
            providerAccountID?: string;
            provider?: string;
        }): OAuth {
            const message = new OAuth({});
            if (data.oauth_token != null) {
                message.oauth_token = data.oauth_token;
            }
            if (data.expires_in != null) {
                message.expires_in = data.expires_in;
            }
            if (data.expires_at != null) {
                message.expires_at = data.expires_at;
            }
            if (data.providerAccountID != null) {
                message.providerAccountID = data.providerAccountID;
            }
            if (data.provider != null) {
                message.provider = data.provider;
            }
            return message;
        }
        toObject() {
            const data: {
                oauth_token?: string;
                expires_in?: string;
                expires_at?: string;
                providerAccountID?: string;
                provider?: string;
            } = {};
            if (this.oauth_token != null) {
                data.oauth_token = this.oauth_token;
            }
            if (this.expires_in != null) {
                data.expires_in = this.expires_in;
            }
            if (this.expires_at != null) {
                data.expires_at = this.expires_at;
            }
            if (this.providerAccountID != null) {
                data.providerAccountID = this.providerAccountID;
            }
            if (this.provider != null) {
                data.provider = this.provider;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.oauth_token.length)
                writer.writeString(1, this.oauth_token);
            if (this.expires_in.length)
                writer.writeString(2, this.expires_in);
            if (this.expires_at.length)
                writer.writeString(3, this.expires_at);
            if (this.providerAccountID.length)
                writer.writeString(4, this.providerAccountID);
            if (this.provider.length)
                writer.writeString(5, this.provider);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): OAuth {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new OAuth();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.oauth_token = reader.readString();
                        break;
                    case 2:
                        message.expires_in = reader.readString();
                        break;
                    case 3:
                        message.expires_at = reader.readString();
                        break;
                    case 4:
                        message.providerAccountID = reader.readString();
                        break;
                    case 5:
                        message.provider = reader.readString();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): OAuth {
            return OAuth.deserialize(bytes);
        }
    }
    export class Token extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            uid?: string;
            email?: string;
            access_token?: string;
            refresh_token?: string;
            status?: Status;
            error_message?: string;
            access_token_expiration?: dependency_1.google.protobuf.Timestamp;
            refresh_token_expiration?: dependency_1.google.protobuf.Timestamp;
            mfa_required?: boolean;
            last_login?: dependency_1.google.protobuf.Timestamp;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("uid" in data && data.uid != undefined) {
                    this.uid = data.uid;
                }
                if ("email" in data && data.email != undefined) {
                    this.email = data.email;
                }
                if ("access_token" in data && data.access_token != undefined) {
                    this.access_token = data.access_token;
                }
                if ("refresh_token" in data && data.refresh_token != undefined) {
                    this.refresh_token = data.refresh_token;
                }
                if ("status" in data && data.status != undefined) {
                    this.status = data.status;
                }
                if ("error_message" in data && data.error_message != undefined) {
                    this.error_message = data.error_message;
                }
                if ("access_token_expiration" in data && data.access_token_expiration != undefined) {
                    this.access_token_expiration = data.access_token_expiration;
                }
                if ("refresh_token_expiration" in data && data.refresh_token_expiration != undefined) {
                    this.refresh_token_expiration = data.refresh_token_expiration;
                }
                if ("mfa_required" in data && data.mfa_required != undefined) {
                    this.mfa_required = data.mfa_required;
                }
                if ("last_login" in data && data.last_login != undefined) {
                    this.last_login = data.last_login;
                }
            }
        }
        get uid() {
            return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
        }
        set uid(value: string) {
            pb_1.Message.setField(this, 1, value);
        }
        get email() {
            return pb_1.Message.getFieldWithDefault(this, 2, "") as string;
        }
        set email(value: string) {
            pb_1.Message.setField(this, 2, value);
        }
        get access_token() {
            return pb_1.Message.getFieldWithDefault(this, 3, "") as string;
        }
        set access_token(value: string) {
            pb_1.Message.setField(this, 3, value);
        }
        get refresh_token() {
            return pb_1.Message.getFieldWithDefault(this, 4, "") as string;
        }
        set refresh_token(value: string) {
            pb_1.Message.setField(this, 4, value);
        }
        get status() {
            return pb_1.Message.getFieldWithDefault(this, 5, Status.AUTH_SUCCESS) as Status;
        }
        set status(value: Status) {
            pb_1.Message.setField(this, 5, value);
        }
        get error_message() {
            return pb_1.Message.getFieldWithDefault(this, 6, "") as string;
        }
        set error_message(value: string) {
            pb_1.Message.setField(this, 6, value);
        }
        get access_token_expiration() {
            return pb_1.Message.getWrapperField(this, dependency_1.google.protobuf.Timestamp, 7) as dependency_1.google.protobuf.Timestamp;
        }
        set access_token_expiration(value: dependency_1.google.protobuf.Timestamp) {
            pb_1.Message.setWrapperField(this, 7, value);
        }
        get has_access_token_expiration() {
            return pb_1.Message.getField(this, 7) != null;
        }
        get refresh_token_expiration() {
            return pb_1.Message.getWrapperField(this, dependency_1.google.protobuf.Timestamp, 8) as dependency_1.google.protobuf.Timestamp;
        }
        set refresh_token_expiration(value: dependency_1.google.protobuf.Timestamp) {
            pb_1.Message.setWrapperField(this, 8, value);
        }
        get has_refresh_token_expiration() {
            return pb_1.Message.getField(this, 8) != null;
        }
        get mfa_required() {
            return pb_1.Message.getFieldWithDefault(this, 9, false) as boolean;
        }
        set mfa_required(value: boolean) {
            pb_1.Message.setField(this, 9, value);
        }
        get last_login() {
            return pb_1.Message.getWrapperField(this, dependency_1.google.protobuf.Timestamp, 10) as dependency_1.google.protobuf.Timestamp;
        }
        set last_login(value: dependency_1.google.protobuf.Timestamp) {
            pb_1.Message.setWrapperField(this, 10, value);
        }
        get has_last_login() {
            return pb_1.Message.getField(this, 10) != null;
        }
        static fromObject(data: {
            uid?: string;
            email?: string;
            access_token?: string;
            refresh_token?: string;
            status?: Status;
            error_message?: string;
            access_token_expiration?: ReturnType<typeof dependency_1.google.protobuf.Timestamp.prototype.toObject>;
            refresh_token_expiration?: ReturnType<typeof dependency_1.google.protobuf.Timestamp.prototype.toObject>;
            mfa_required?: boolean;
            last_login?: ReturnType<typeof dependency_1.google.protobuf.Timestamp.prototype.toObject>;
        }): Token {
            const message = new Token({});
            if (data.uid != null) {
                message.uid = data.uid;
            }
            if (data.email != null) {
                message.email = data.email;
            }
            if (data.access_token != null) {
                message.access_token = data.access_token;
            }
            if (data.refresh_token != null) {
                message.refresh_token = data.refresh_token;
            }
            if (data.status != null) {
                message.status = data.status;
            }
            if (data.error_message != null) {
                message.error_message = data.error_message;
            }
            if (data.access_token_expiration != null) {
                message.access_token_expiration = dependency_1.google.protobuf.Timestamp.fromObject(data.access_token_expiration);
            }
            if (data.refresh_token_expiration != null) {
                message.refresh_token_expiration = dependency_1.google.protobuf.Timestamp.fromObject(data.refresh_token_expiration);
            }
            if (data.mfa_required != null) {
                message.mfa_required = data.mfa_required;
            }
            if (data.last_login != null) {
                message.last_login = dependency_1.google.protobuf.Timestamp.fromObject(data.last_login);
            }
            return message;
        }
        toObject() {
            const data: {
                uid?: string;
                email?: string;
                access_token?: string;
                refresh_token?: string;
                status?: Status;
                error_message?: string;
                access_token_expiration?: ReturnType<typeof dependency_1.google.protobuf.Timestamp.prototype.toObject>;
                refresh_token_expiration?: ReturnType<typeof dependency_1.google.protobuf.Timestamp.prototype.toObject>;
                mfa_required?: boolean;
                last_login?: ReturnType<typeof dependency_1.google.protobuf.Timestamp.prototype.toObject>;
            } = {};
            if (this.uid != null) {
                data.uid = this.uid;
            }
            if (this.email != null) {
                data.email = this.email;
            }
            if (this.access_token != null) {
                data.access_token = this.access_token;
            }
            if (this.refresh_token != null) {
                data.refresh_token = this.refresh_token;
            }
            if (this.status != null) {
                data.status = this.status;
            }
            if (this.error_message != null) {
                data.error_message = this.error_message;
            }
            if (this.access_token_expiration != null) {
                data.access_token_expiration = this.access_token_expiration.toObject();
            }
            if (this.refresh_token_expiration != null) {
                data.refresh_token_expiration = this.refresh_token_expiration.toObject();
            }
            if (this.mfa_required != null) {
                data.mfa_required = this.mfa_required;
            }
            if (this.last_login != null) {
                data.last_login = this.last_login.toObject();
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.uid.length)
                writer.writeString(1, this.uid);
            if (this.email.length)
                writer.writeString(2, this.email);
            if (this.access_token.length)
                writer.writeString(3, this.access_token);
            if (this.refresh_token.length)
                writer.writeString(4, this.refresh_token);
            if (this.status != Status.AUTH_SUCCESS)
                writer.writeEnum(5, this.status);
            if (this.error_message.length)
                writer.writeString(6, this.error_message);
            if (this.has_access_token_expiration)
                writer.writeMessage(7, this.access_token_expiration, () => this.access_token_expiration.serialize(writer));
            if (this.has_refresh_token_expiration)
                writer.writeMessage(8, this.refresh_token_expiration, () => this.refresh_token_expiration.serialize(writer));
            if (this.mfa_required != false)
                writer.writeBool(9, this.mfa_required);
            if (this.has_last_login)
                writer.writeMessage(10, this.last_login, () => this.last_login.serialize(writer));
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): Token {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new Token();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.uid = reader.readString();
                        break;
                    case 2:
                        message.email = reader.readString();
                        break;
                    case 3:
                        message.access_token = reader.readString();
                        break;
                    case 4:
                        message.refresh_token = reader.readString();
                        break;
                    case 5:
                        message.status = reader.readEnum();
                        break;
                    case 6:
                        message.error_message = reader.readString();
                        break;
                    case 7:
                        reader.readMessage(message.access_token_expiration, () => message.access_token_expiration = dependency_1.google.protobuf.Timestamp.deserialize(reader));
                        break;
                    case 8:
                        reader.readMessage(message.refresh_token_expiration, () => message.refresh_token_expiration = dependency_1.google.protobuf.Timestamp.deserialize(reader));
                        break;
                    case 9:
                        message.mfa_required = reader.readBool();
                        break;
                    case 10:
                        reader.readMessage(message.last_login, () => message.last_login = dependency_1.google.protobuf.Timestamp.deserialize(reader));
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): Token {
            return Token.deserialize(bytes);
        }
    }
    export class Credentials extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            email?: string;
            password?: string;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("email" in data && data.email != undefined) {
                    this.email = data.email;
                }
                if ("password" in data && data.password != undefined) {
                    this.password = data.password;
                }
            }
        }
        get email() {
            return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
        }
        set email(value: string) {
            pb_1.Message.setField(this, 1, value);
        }
        get password() {
            return pb_1.Message.getFieldWithDefault(this, 2, "") as string;
        }
        set password(value: string) {
            pb_1.Message.setField(this, 2, value);
        }
        static fromObject(data: {
            email?: string;
            password?: string;
        }): Credentials {
            const message = new Credentials({});
            if (data.email != null) {
                message.email = data.email;
            }
            if (data.password != null) {
                message.password = data.password;
            }
            return message;
        }
        toObject() {
            const data: {
                email?: string;
                password?: string;
            } = {};
            if (this.email != null) {
                data.email = this.email;
            }
            if (this.password != null) {
                data.password = this.password;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.email.length)
                writer.writeString(1, this.email);
            if (this.password.length)
                writer.writeString(2, this.password);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): Credentials {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new Credentials();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.email = reader.readString();
                        break;
                    case 2:
                        message.password = reader.readString();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): Credentials {
            return Credentials.deserialize(bytes);
        }
    }
    export class AuthRequest extends pb_1.Message {
        #one_of_decls: number[][] = [[1, 2]];
        constructor(data?: any[] | ({} & (({
            credentials?: Credentials;
            oauth?: never;
        } | {
            credentials?: never;
            oauth?: OAuth;
        })))) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("credentials" in data && data.credentials != undefined) {
                    this.credentials = data.credentials;
                }
                if ("oauth" in data && data.oauth != undefined) {
                    this.oauth = data.oauth;
                }
            }
        }
        get credentials() {
            return pb_1.Message.getWrapperField(this, Credentials, 1) as Credentials;
        }
        set credentials(value: Credentials) {
            pb_1.Message.setOneofWrapperField(this, 1, this.#one_of_decls[0], value);
        }
        get has_credentials() {
            return pb_1.Message.getField(this, 1) != null;
        }
        get oauth() {
            return pb_1.Message.getWrapperField(this, OAuth, 2) as OAuth;
        }
        set oauth(value: OAuth) {
            pb_1.Message.setOneofWrapperField(this, 2, this.#one_of_decls[0], value);
        }
        get has_oauth() {
            return pb_1.Message.getField(this, 2) != null;
        }
        get data() {
            const cases: {
                [index: number]: "none" | "credentials" | "oauth";
            } = {
                0: "none",
                1: "credentials",
                2: "oauth"
            };
            return cases[pb_1.Message.computeOneofCase(this, [1, 2])];
        }
        static fromObject(data: {
            credentials?: ReturnType<typeof Credentials.prototype.toObject>;
            oauth?: ReturnType<typeof OAuth.prototype.toObject>;
        }): AuthRequest {
            const message = new AuthRequest({});
            if (data.credentials != null) {
                message.credentials = Credentials.fromObject(data.credentials);
            }
            if (data.oauth != null) {
                message.oauth = OAuth.fromObject(data.oauth);
            }
            return message;
        }
        toObject() {
            const data: {
                credentials?: ReturnType<typeof Credentials.prototype.toObject>;
                oauth?: ReturnType<typeof OAuth.prototype.toObject>;
            } = {};
            if (this.credentials != null) {
                data.credentials = this.credentials.toObject();
            }
            if (this.oauth != null) {
                data.oauth = this.oauth.toObject();
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.has_credentials)
                writer.writeMessage(1, this.credentials, () => this.credentials.serialize(writer));
            if (this.has_oauth)
                writer.writeMessage(2, this.oauth, () => this.oauth.serialize(writer));
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): AuthRequest {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new AuthRequest();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        reader.readMessage(message.credentials, () => message.credentials = Credentials.deserialize(reader));
                        break;
                    case 2:
                        reader.readMessage(message.oauth, () => message.oauth = OAuth.deserialize(reader));
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): AuthRequest {
            return AuthRequest.deserialize(bytes);
        }
    }
    export class AuthToken extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            token?: string;
            status?: Status;
            error_message?: string;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("token" in data && data.token != undefined) {
                    this.token = data.token;
                }
                if ("status" in data && data.status != undefined) {
                    this.status = data.status;
                }
                if ("error_message" in data && data.error_message != undefined) {
                    this.error_message = data.error_message;
                }
            }
        }
        get token() {
            return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
        }
        set token(value: string) {
            pb_1.Message.setField(this, 1, value);
        }
        get status() {
            return pb_1.Message.getFieldWithDefault(this, 2, Status.AUTH_SUCCESS) as Status;
        }
        set status(value: Status) {
            pb_1.Message.setField(this, 2, value);
        }
        get error_message() {
            return pb_1.Message.getFieldWithDefault(this, 3, "") as string;
        }
        set error_message(value: string) {
            pb_1.Message.setField(this, 3, value);
        }
        static fromObject(data: {
            token?: string;
            status?: Status;
            error_message?: string;
        }): AuthToken {
            const message = new AuthToken({});
            if (data.token != null) {
                message.token = data.token;
            }
            if (data.status != null) {
                message.status = data.status;
            }
            if (data.error_message != null) {
                message.error_message = data.error_message;
            }
            return message;
        }
        toObject() {
            const data: {
                token?: string;
                status?: Status;
                error_message?: string;
            } = {};
            if (this.token != null) {
                data.token = this.token;
            }
            if (this.status != null) {
                data.status = this.status;
            }
            if (this.error_message != null) {
                data.error_message = this.error_message;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.token.length)
                writer.writeString(1, this.token);
            if (this.status != Status.AUTH_SUCCESS)
                writer.writeEnum(2, this.status);
            if (this.error_message.length)
                writer.writeString(3, this.error_message);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): AuthToken {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new AuthToken();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.token = reader.readString();
                        break;
                    case 2:
                        message.status = reader.readEnum();
                        break;
                    case 3:
                        message.error_message = reader.readString();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): AuthToken {
            return AuthToken.deserialize(bytes);
        }
    }
    export class RefreshToken extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            token?: string;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("token" in data && data.token != undefined) {
                    this.token = data.token;
                }
            }
        }
        get token() {
            return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
        }
        set token(value: string) {
            pb_1.Message.setField(this, 1, value);
        }
        static fromObject(data: {
            token?: string;
        }): RefreshToken {
            const message = new RefreshToken({});
            if (data.token != null) {
                message.token = data.token;
            }
            return message;
        }
        toObject() {
            const data: {
                token?: string;
            } = {};
            if (this.token != null) {
                data.token = this.token;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.token.length)
                writer.writeString(1, this.token);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): RefreshToken {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new RefreshToken();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.token = reader.readString();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): RefreshToken {
            return RefreshToken.deserialize(bytes);
        }
    }
    export class Revoke extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            message?: string;
            status?: Status;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("message" in data && data.message != undefined) {
                    this.message = data.message;
                }
                if ("status" in data && data.status != undefined) {
                    this.status = data.status;
                }
            }
        }
        get message() {
            return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
        }
        set message(value: string) {
            pb_1.Message.setField(this, 1, value);
        }
        get status() {
            return pb_1.Message.getFieldWithDefault(this, 2, Status.AUTH_SUCCESS) as Status;
        }
        set status(value: Status) {
            pb_1.Message.setField(this, 2, value);
        }
        static fromObject(data: {
            message?: string;
            status?: Status;
        }): Revoke {
            const message = new Revoke({});
            if (data.message != null) {
                message.message = data.message;
            }
            if (data.status != null) {
                message.status = data.status;
            }
            return message;
        }
        toObject() {
            const data: {
                message?: string;
                status?: Status;
            } = {};
            if (this.message != null) {
                data.message = this.message;
            }
            if (this.status != null) {
                data.status = this.status;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.message.length)
                writer.writeString(1, this.message);
            if (this.status != Status.AUTH_SUCCESS)
                writer.writeEnum(2, this.status);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): Revoke {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new Revoke();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.message = reader.readString();
                        break;
                    case 2:
                        message.status = reader.readEnum();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): Revoke {
            return Revoke.deserialize(bytes);
        }
    }
    export class AccessToken extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            token?: string;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("token" in data && data.token != undefined) {
                    this.token = data.token;
                }
            }
        }
        get token() {
            return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
        }
        set token(value: string) {
            pb_1.Message.setField(this, 1, value);
        }
        static fromObject(data: {
            token?: string;
        }): AccessToken {
            const message = new AccessToken({});
            if (data.token != null) {
                message.token = data.token;
            }
            return message;
        }
        toObject() {
            const data: {
                token?: string;
            } = {};
            if (this.token != null) {
                data.token = this.token;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.token.length)
                writer.writeString(1, this.token);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): AccessToken {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new AccessToken();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.token = reader.readString();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): AccessToken {
            return AccessToken.deserialize(bytes);
        }
    }
    export class Login extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            canLogin?: boolean;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("canLogin" in data && data.canLogin != undefined) {
                    this.canLogin = data.canLogin;
                }
            }
        }
        get canLogin() {
            return pb_1.Message.getFieldWithDefault(this, 1, false) as boolean;
        }
        set canLogin(value: boolean) {
            pb_1.Message.setField(this, 1, value);
        }
        static fromObject(data: {
            canLogin?: boolean;
        }): Login {
            const message = new Login({});
            if (data.canLogin != null) {
                message.canLogin = data.canLogin;
            }
            return message;
        }
        toObject() {
            const data: {
                canLogin?: boolean;
            } = {};
            if (this.canLogin != null) {
                data.canLogin = this.canLogin;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.canLogin != false)
                writer.writeBool(1, this.canLogin);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): Login {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new Login();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.canLogin = reader.readBool();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): Login {
            return Login.deserialize(bytes);
        }
    }
    export class User extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            name?: string;
            email?: string;
            password?: string;
            provider?: string;
            provider_uid?: string;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("name" in data && data.name != undefined) {
                    this.name = data.name;
                }
                if ("email" in data && data.email != undefined) {
                    this.email = data.email;
                }
                if ("password" in data && data.password != undefined) {
                    this.password = data.password;
                }
                if ("provider" in data && data.provider != undefined) {
                    this.provider = data.provider;
                }
                if ("provider_uid" in data && data.provider_uid != undefined) {
                    this.provider_uid = data.provider_uid;
                }
            }
        }
        get name() {
            return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
        }
        set name(value: string) {
            pb_1.Message.setField(this, 1, value);
        }
        get email() {
            return pb_1.Message.getFieldWithDefault(this, 2, "") as string;
        }
        set email(value: string) {
            pb_1.Message.setField(this, 2, value);
        }
        get password() {
            return pb_1.Message.getFieldWithDefault(this, 3, "") as string;
        }
        set password(value: string) {
            pb_1.Message.setField(this, 3, value);
        }
        get provider() {
            return pb_1.Message.getFieldWithDefault(this, 4, "") as string;
        }
        set provider(value: string) {
            pb_1.Message.setField(this, 4, value);
        }
        get provider_uid() {
            return pb_1.Message.getFieldWithDefault(this, 5, "") as string;
        }
        set provider_uid(value: string) {
            pb_1.Message.setField(this, 5, value);
        }
        static fromObject(data: {
            name?: string;
            email?: string;
            password?: string;
            provider?: string;
            provider_uid?: string;
        }): User {
            const message = new User({});
            if (data.name != null) {
                message.name = data.name;
            }
            if (data.email != null) {
                message.email = data.email;
            }
            if (data.password != null) {
                message.password = data.password;
            }
            if (data.provider != null) {
                message.provider = data.provider;
            }
            if (data.provider_uid != null) {
                message.provider_uid = data.provider_uid;
            }
            return message;
        }
        toObject() {
            const data: {
                name?: string;
                email?: string;
                password?: string;
                provider?: string;
                provider_uid?: string;
            } = {};
            if (this.name != null) {
                data.name = this.name;
            }
            if (this.email != null) {
                data.email = this.email;
            }
            if (this.password != null) {
                data.password = this.password;
            }
            if (this.provider != null) {
                data.provider = this.provider;
            }
            if (this.provider_uid != null) {
                data.provider_uid = this.provider_uid;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.name.length)
                writer.writeString(1, this.name);
            if (this.email.length)
                writer.writeString(2, this.email);
            if (this.password.length)
                writer.writeString(3, this.password);
            if (this.provider.length)
                writer.writeString(4, this.provider);
            if (this.provider_uid.length)
                writer.writeString(5, this.provider_uid);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): User {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new User();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.name = reader.readString();
                        break;
                    case 2:
                        message.email = reader.readString();
                        break;
                    case 3:
                        message.password = reader.readString();
                        break;
                    case 4:
                        message.provider = reader.readString();
                        break;
                    case 5:
                        message.provider_uid = reader.readString();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): User {
            return User.deserialize(bytes);
        }
    }
    export class RegisterStatus extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            status?: Status;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("status" in data && data.status != undefined) {
                    this.status = data.status;
                }
            }
        }
        get status() {
            return pb_1.Message.getFieldWithDefault(this, 1, Status.AUTH_SUCCESS) as Status;
        }
        set status(value: Status) {
            pb_1.Message.setField(this, 1, value);
        }
        static fromObject(data: {
            status?: Status;
        }): RegisterStatus {
            const message = new RegisterStatus({});
            if (data.status != null) {
                message.status = data.status;
            }
            return message;
        }
        toObject() {
            const data: {
                status?: Status;
            } = {};
            if (this.status != null) {
                data.status = this.status;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.status != Status.AUTH_SUCCESS)
                writer.writeEnum(1, this.status);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): RegisterStatus {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new RegisterStatus();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.status = reader.readEnum();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): RegisterStatus {
            return RegisterStatus.deserialize(bytes);
        }
    }
    interface GrpcUnaryServiceInterface<P, R> {
        (message: P, metadata: grpc_1.Metadata, options: grpc_1.CallOptions, callback: grpc_1.requestCallback<R>): grpc_1.ClientUnaryCall;
        (message: P, metadata: grpc_1.Metadata, callback: grpc_1.requestCallback<R>): grpc_1.ClientUnaryCall;
        (message: P, options: grpc_1.CallOptions, callback: grpc_1.requestCallback<R>): grpc_1.ClientUnaryCall;
        (message: P, callback: grpc_1.requestCallback<R>): grpc_1.ClientUnaryCall;
    }
    interface GrpcStreamServiceInterface<P, R> {
        (message: P, metadata: grpc_1.Metadata, options?: grpc_1.CallOptions): grpc_1.ClientReadableStream<R>;
        (message: P, options?: grpc_1.CallOptions): grpc_1.ClientReadableStream<R>;
    }
    interface GrpWritableServiceInterface<P, R> {
        (metadata: grpc_1.Metadata, options: grpc_1.CallOptions, callback: grpc_1.requestCallback<R>): grpc_1.ClientWritableStream<P>;
        (metadata: grpc_1.Metadata, callback: grpc_1.requestCallback<R>): grpc_1.ClientWritableStream<P>;
        (options: grpc_1.CallOptions, callback: grpc_1.requestCallback<R>): grpc_1.ClientWritableStream<P>;
        (callback: grpc_1.requestCallback<R>): grpc_1.ClientWritableStream<P>;
    }
    interface GrpcChunkServiceInterface<P, R> {
        (metadata: grpc_1.Metadata, options?: grpc_1.CallOptions): grpc_1.ClientDuplexStream<P, R>;
        (options?: grpc_1.CallOptions): grpc_1.ClientDuplexStream<P, R>;
    }
    interface GrpcPromiseServiceInterface<P, R> {
        (message: P, metadata: grpc_1.Metadata, options?: grpc_1.CallOptions): Promise<R>;
        (message: P, options?: grpc_1.CallOptions): Promise<R>;
    }
    export abstract class UnimplementedauthService {
        static definition = {
            auth: {
                path: "/auth.auth/auth",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: AuthRequest) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => AuthRequest.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: Token) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => Token.deserialize(new Uint8Array(bytes))
            },
            token: {
                path: "/auth.auth/token",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: RefreshToken) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => RefreshToken.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: AuthToken) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => AuthToken.deserialize(new Uint8Array(bytes))
            },
            revoke: {
                path: "/auth.auth/revoke",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: RefreshToken) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => RefreshToken.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: Revoke) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => Revoke.deserialize(new Uint8Array(bytes))
            },
            register: {
                path: "/auth.auth/register",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: User) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => User.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: RegisterStatus) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => RegisterStatus.deserialize(new Uint8Array(bytes))
            }
        };
        [method: string]: grpc_1.UntypedHandleCall;
        abstract auth(call: grpc_1.ServerUnaryCall<AuthRequest, Token>, callback: grpc_1.sendUnaryData<Token>): void;
        abstract token(call: grpc_1.ServerUnaryCall<RefreshToken, AuthToken>, callback: grpc_1.sendUnaryData<AuthToken>): void;
        abstract revoke(call: grpc_1.ServerUnaryCall<RefreshToken, Revoke>, callback: grpc_1.sendUnaryData<Revoke>): void;
        abstract register(call: grpc_1.ServerUnaryCall<User, RegisterStatus>, callback: grpc_1.sendUnaryData<RegisterStatus>): void;
    }
    export class authClient extends grpc_1.makeGenericClientConstructor(UnimplementedauthService.definition, "auth", {}) {
        constructor(address: string, credentials: grpc_1.ChannelCredentials, options?: Partial<grpc_1.ChannelOptions>) {
            super(address, credentials, options);
        }
        auth: GrpcUnaryServiceInterface<AuthRequest, Token> = (message: AuthRequest, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<Token>, options?: grpc_1.CallOptions | grpc_1.requestCallback<Token>, callback?: grpc_1.requestCallback<Token>): grpc_1.ClientUnaryCall => {
            return super.auth(message, metadata, options, callback);
        };
        token: GrpcUnaryServiceInterface<RefreshToken, AuthToken> = (message: RefreshToken, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<AuthToken>, options?: grpc_1.CallOptions | grpc_1.requestCallback<AuthToken>, callback?: grpc_1.requestCallback<AuthToken>): grpc_1.ClientUnaryCall => {
            return super.token(message, metadata, options, callback);
        };
        revoke: GrpcUnaryServiceInterface<RefreshToken, Revoke> = (message: RefreshToken, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<Revoke>, options?: grpc_1.CallOptions | grpc_1.requestCallback<Revoke>, callback?: grpc_1.requestCallback<Revoke>): grpc_1.ClientUnaryCall => {
            return super.revoke(message, metadata, options, callback);
        };
        register: GrpcUnaryServiceInterface<User, RegisterStatus> = (message: User, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<RegisterStatus>, options?: grpc_1.CallOptions | grpc_1.requestCallback<RegisterStatus>, callback?: grpc_1.requestCallback<RegisterStatus>): grpc_1.ClientUnaryCall => {
            return super.register(message, metadata, options, callback);
        };
    }
}
