/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 5.28.3
 * source: events.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as dependency_1 from "./google\\protobuf\\timestamp";
import * as pb_1 from "google-protobuf";
import * as grpc_1 from "@grpc/grpc-js";
export namespace events {
    export enum SuccessCode {
        SUCCESS_UNKNOWN = 0,
        MESSAGE_SENT = 1,
        KEY_EXCHANGE_COMPLETED = 2,
        MESSAGE_DELIVERED = 3,
        SESSION_ESTABLISHED = 4
    }
    export enum MessageCommand {
        MESSAGE_SEND = 0,
        MESSAGE_RECEIVE = 1,
        UPDATE_TIMESTAMP = 2,
        EDIT_MESSAGE = 3,
        DELETE_MESSAGE = 4,
        FORWARD_MESSAGE = 5,
        RETRY_SEND = 6,
        MARK_AS_IMPORTANT = 7,
        ARCHIVE_MESSAGE = 8,
        UNARCHIVE_MESSAGE = 9,
        MARK_AS_SPAM = 10,
        MARK_AS_READ = 11,
        MARK_AS_UNREAD = 12,
        REVOKE_MESSAGE = 13,
        PIN_MESSAGE = 14,
        UNPIN_MESSAGE = 15
    }
    export enum MessageStatus {
        PENDING = 0,
        DELIVERED = 1,
        READ = 2,
        FAILED = 3
    }
    export class Message extends pb_1.Message {
        #one_of_decls: number[][] = [[5, 6, 7, 8, 9, 10, 11]];
        constructor(data?: any[] | ({
            status?: MessageStatus;
            send_time?: dependency_1.google.protobuf.Timestamp;
            delivered_time?: dependency_1.google.protobuf.Timestamp;
            read_time?: dependency_1.google.protobuf.Timestamp;
            uid?: string;
        } & (({
            text?: string;
            audio?: never;
            video?: never;
            document?: never;
            image?: never;
            file?: never;
            url?: never;
        } | {
            text?: never;
            audio?: Uint8Array;
            video?: never;
            document?: never;
            image?: never;
            file?: never;
            url?: never;
        } | {
            text?: never;
            audio?: never;
            video?: Uint8Array;
            document?: never;
            image?: never;
            file?: never;
            url?: never;
        } | {
            text?: never;
            audio?: never;
            video?: never;
            document?: Uint8Array;
            image?: never;
            file?: never;
            url?: never;
        } | {
            text?: never;
            audio?: never;
            video?: never;
            document?: never;
            image?: Uint8Array;
            file?: never;
            url?: never;
        } | {
            text?: never;
            audio?: never;
            video?: never;
            document?: never;
            image?: never;
            file?: Uint8Array;
            url?: never;
        } | {
            text?: never;
            audio?: never;
            video?: never;
            document?: never;
            image?: never;
            file?: never;
            url?: string;
        })))) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("status" in data && data.status != undefined) {
                    this.status = data.status;
                }
                if ("send_time" in data && data.send_time != undefined) {
                    this.send_time = data.send_time;
                }
                if ("delivered_time" in data && data.delivered_time != undefined) {
                    this.delivered_time = data.delivered_time;
                }
                if ("read_time" in data && data.read_time != undefined) {
                    this.read_time = data.read_time;
                }
                if ("text" in data && data.text != undefined) {
                    this.text = data.text;
                }
                if ("audio" in data && data.audio != undefined) {
                    this.audio = data.audio;
                }
                if ("video" in data && data.video != undefined) {
                    this.video = data.video;
                }
                if ("document" in data && data.document != undefined) {
                    this.document = data.document;
                }
                if ("image" in data && data.image != undefined) {
                    this.image = data.image;
                }
                if ("file" in data && data.file != undefined) {
                    this.file = data.file;
                }
                if ("url" in data && data.url != undefined) {
                    this.url = data.url;
                }
                if ("uid" in data && data.uid != undefined) {
                    this.uid = data.uid;
                }
            }
        }
        get status() {
            return pb_1.Message.getFieldWithDefault(this, 1, MessageStatus.PENDING) as MessageStatus;
        }
        set status(value: MessageStatus) {
            pb_1.Message.setField(this, 1, value);
        }
        get send_time() {
            return pb_1.Message.getWrapperField(this, dependency_1.google.protobuf.Timestamp, 2) as dependency_1.google.protobuf.Timestamp;
        }
        set send_time(value: dependency_1.google.protobuf.Timestamp) {
            pb_1.Message.setWrapperField(this, 2, value);
        }
        get has_send_time() {
            return pb_1.Message.getField(this, 2) != null;
        }
        get delivered_time() {
            return pb_1.Message.getWrapperField(this, dependency_1.google.protobuf.Timestamp, 3) as dependency_1.google.protobuf.Timestamp;
        }
        set delivered_time(value: dependency_1.google.protobuf.Timestamp) {
            pb_1.Message.setWrapperField(this, 3, value);
        }
        get has_delivered_time() {
            return pb_1.Message.getField(this, 3) != null;
        }
        get read_time() {
            return pb_1.Message.getWrapperField(this, dependency_1.google.protobuf.Timestamp, 4) as dependency_1.google.protobuf.Timestamp;
        }
        set read_time(value: dependency_1.google.protobuf.Timestamp) {
            pb_1.Message.setWrapperField(this, 4, value);
        }
        get has_read_time() {
            return pb_1.Message.getField(this, 4) != null;
        }
        get text() {
            return pb_1.Message.getFieldWithDefault(this, 5, "") as string;
        }
        set text(value: string) {
            pb_1.Message.setOneofField(this, 5, this.#one_of_decls[0], value);
        }
        get has_text() {
            return pb_1.Message.getField(this, 5) != null;
        }
        get audio() {
            return pb_1.Message.getFieldWithDefault(this, 6, new Uint8Array(0)) as Uint8Array;
        }
        set audio(value: Uint8Array) {
            pb_1.Message.setOneofField(this, 6, this.#one_of_decls[0], value);
        }
        get has_audio() {
            return pb_1.Message.getField(this, 6) != null;
        }
        get video() {
            return pb_1.Message.getFieldWithDefault(this, 7, new Uint8Array(0)) as Uint8Array;
        }
        set video(value: Uint8Array) {
            pb_1.Message.setOneofField(this, 7, this.#one_of_decls[0], value);
        }
        get has_video() {
            return pb_1.Message.getField(this, 7) != null;
        }
        get document() {
            return pb_1.Message.getFieldWithDefault(this, 8, new Uint8Array(0)) as Uint8Array;
        }
        set document(value: Uint8Array) {
            pb_1.Message.setOneofField(this, 8, this.#one_of_decls[0], value);
        }
        get has_document() {
            return pb_1.Message.getField(this, 8) != null;
        }
        get image() {
            return pb_1.Message.getFieldWithDefault(this, 9, new Uint8Array(0)) as Uint8Array;
        }
        set image(value: Uint8Array) {
            pb_1.Message.setOneofField(this, 9, this.#one_of_decls[0], value);
        }
        get has_image() {
            return pb_1.Message.getField(this, 9) != null;
        }
        get file() {
            return pb_1.Message.getFieldWithDefault(this, 10, new Uint8Array(0)) as Uint8Array;
        }
        set file(value: Uint8Array) {
            pb_1.Message.setOneofField(this, 10, this.#one_of_decls[0], value);
        }
        get has_file() {
            return pb_1.Message.getField(this, 10) != null;
        }
        get url() {
            return pb_1.Message.getFieldWithDefault(this, 11, "") as string;
        }
        set url(value: string) {
            pb_1.Message.setOneofField(this, 11, this.#one_of_decls[0], value);
        }
        get has_url() {
            return pb_1.Message.getField(this, 11) != null;
        }
        get uid() {
            return pb_1.Message.getFieldWithDefault(this, 13, "") as string;
        }
        set uid(value: string) {
            pb_1.Message.setField(this, 13, value);
        }
        get data() {
            const cases: {
                [index: number]: "none" | "text" | "audio" | "video" | "document" | "image" | "file" | "url";
            } = {
                0: "none",
                5: "text",
                6: "audio",
                7: "video",
                8: "document",
                9: "image",
                10: "file",
                11: "url"
            };
            return cases[pb_1.Message.computeOneofCase(this, [5, 6, 7, 8, 9, 10, 11])];
        }
        static fromObject(data: {
            status?: MessageStatus;
            send_time?: ReturnType<typeof dependency_1.google.protobuf.Timestamp.prototype.toObject>;
            delivered_time?: ReturnType<typeof dependency_1.google.protobuf.Timestamp.prototype.toObject>;
            read_time?: ReturnType<typeof dependency_1.google.protobuf.Timestamp.prototype.toObject>;
            text?: string;
            audio?: Uint8Array;
            video?: Uint8Array;
            document?: Uint8Array;
            image?: Uint8Array;
            file?: Uint8Array;
            url?: string;
            uid?: string;
        }): Message {
            const message = new Message({});
            if (data.status != null) {
                message.status = data.status;
            }
            if (data.send_time != null) {
                message.send_time = dependency_1.google.protobuf.Timestamp.fromObject(data.send_time);
            }
            if (data.delivered_time != null) {
                message.delivered_time = dependency_1.google.protobuf.Timestamp.fromObject(data.delivered_time);
            }
            if (data.read_time != null) {
                message.read_time = dependency_1.google.protobuf.Timestamp.fromObject(data.read_time);
            }
            if (data.text != null) {
                message.text = data.text;
            }
            if (data.audio != null) {
                message.audio = data.audio;
            }
            if (data.video != null) {
                message.video = data.video;
            }
            if (data.document != null) {
                message.document = data.document;
            }
            if (data.image != null) {
                message.image = data.image;
            }
            if (data.file != null) {
                message.file = data.file;
            }
            if (data.url != null) {
                message.url = data.url;
            }
            if (data.uid != null) {
                message.uid = data.uid;
            }
            return message;
        }
        toObject() {
            const data: {
                status?: MessageStatus;
                send_time?: ReturnType<typeof dependency_1.google.protobuf.Timestamp.prototype.toObject>;
                delivered_time?: ReturnType<typeof dependency_1.google.protobuf.Timestamp.prototype.toObject>;
                read_time?: ReturnType<typeof dependency_1.google.protobuf.Timestamp.prototype.toObject>;
                text?: string;
                audio?: Uint8Array;
                video?: Uint8Array;
                document?: Uint8Array;
                image?: Uint8Array;
                file?: Uint8Array;
                url?: string;
                uid?: string;
            } = {};
            if (this.status != null) {
                data.status = this.status;
            }
            if (this.send_time != null) {
                data.send_time = this.send_time.toObject();
            }
            if (this.delivered_time != null) {
                data.delivered_time = this.delivered_time.toObject();
            }
            if (this.read_time != null) {
                data.read_time = this.read_time.toObject();
            }
            if (this.text != null) {
                data.text = this.text;
            }
            if (this.audio != null) {
                data.audio = this.audio;
            }
            if (this.video != null) {
                data.video = this.video;
            }
            if (this.document != null) {
                data.document = this.document;
            }
            if (this.image != null) {
                data.image = this.image;
            }
            if (this.file != null) {
                data.file = this.file;
            }
            if (this.url != null) {
                data.url = this.url;
            }
            if (this.uid != null) {
                data.uid = this.uid;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.status != MessageStatus.PENDING)
                writer.writeEnum(1, this.status);
            if (this.has_send_time)
                writer.writeMessage(2, this.send_time, () => this.send_time.serialize(writer));
            if (this.has_delivered_time)
                writer.writeMessage(3, this.delivered_time, () => this.delivered_time.serialize(writer));
            if (this.has_read_time)
                writer.writeMessage(4, this.read_time, () => this.read_time.serialize(writer));
            if (this.has_text)
                writer.writeString(5, this.text);
            if (this.has_audio)
                writer.writeBytes(6, this.audio);
            if (this.has_video)
                writer.writeBytes(7, this.video);
            if (this.has_document)
                writer.writeBytes(8, this.document);
            if (this.has_image)
                writer.writeBytes(9, this.image);
            if (this.has_file)
                writer.writeBytes(10, this.file);
            if (this.has_url)
                writer.writeString(11, this.url);
            if (this.uid.length)
                writer.writeString(13, this.uid);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): Message {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new Message();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.status = reader.readEnum();
                        break;
                    case 2:
                        reader.readMessage(message.send_time, () => message.send_time = dependency_1.google.protobuf.Timestamp.deserialize(reader));
                        break;
                    case 3:
                        reader.readMessage(message.delivered_time, () => message.delivered_time = dependency_1.google.protobuf.Timestamp.deserialize(reader));
                        break;
                    case 4:
                        reader.readMessage(message.read_time, () => message.read_time = dependency_1.google.protobuf.Timestamp.deserialize(reader));
                        break;
                    case 5:
                        message.text = reader.readString();
                        break;
                    case 6:
                        message.audio = reader.readBytes();
                        break;
                    case 7:
                        message.video = reader.readBytes();
                        break;
                    case 8:
                        message.document = reader.readBytes();
                        break;
                    case 9:
                        message.image = reader.readBytes();
                        break;
                    case 10:
                        message.file = reader.readBytes();
                        break;
                    case 11:
                        message.url = reader.readString();
                        break;
                    case 13:
                        message.uid = reader.readString();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): Message {
            return Message.deserialize(bytes);
        }
    }
    export class MessageEvent extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            command?: MessageCommand;
            event_uid?: string;
            sender_uid?: string;
            dst_uids?: string[];
            message?: Message;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [4], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("command" in data && data.command != undefined) {
                    this.command = data.command;
                }
                if ("event_uid" in data && data.event_uid != undefined) {
                    this.event_uid = data.event_uid;
                }
                if ("sender_uid" in data && data.sender_uid != undefined) {
                    this.sender_uid = data.sender_uid;
                }
                if ("dst_uids" in data && data.dst_uids != undefined) {
                    this.dst_uids = data.dst_uids;
                }
                if ("message" in data && data.message != undefined) {
                    this.message = data.message;
                }
            }
        }
        get command() {
            return pb_1.Message.getFieldWithDefault(this, 1, MessageCommand.MESSAGE_SEND) as MessageCommand;
        }
        set command(value: MessageCommand) {
            pb_1.Message.setField(this, 1, value);
        }
        get event_uid() {
            return pb_1.Message.getFieldWithDefault(this, 2, "") as string;
        }
        set event_uid(value: string) {
            pb_1.Message.setField(this, 2, value);
        }
        get sender_uid() {
            return pb_1.Message.getFieldWithDefault(this, 3, "") as string;
        }
        set sender_uid(value: string) {
            pb_1.Message.setField(this, 3, value);
        }
        get dst_uids() {
            return pb_1.Message.getFieldWithDefault(this, 4, []) as string[];
        }
        set dst_uids(value: string[]) {
            pb_1.Message.setField(this, 4, value);
        }
        get message() {
            return pb_1.Message.getWrapperField(this, Message, 5) as Message;
        }
        set message(value: Message) {
            pb_1.Message.setWrapperField(this, 5, value);
        }
        get has_message() {
            return pb_1.Message.getField(this, 5) != null;
        }
        static fromObject(data: {
            command?: MessageCommand;
            event_uid?: string;
            sender_uid?: string;
            dst_uids?: string[];
            message?: ReturnType<typeof Message.prototype.toObject>;
        }): MessageEvent {
            const message = new MessageEvent({});
            if (data.command != null) {
                message.command = data.command;
            }
            if (data.event_uid != null) {
                message.event_uid = data.event_uid;
            }
            if (data.sender_uid != null) {
                message.sender_uid = data.sender_uid;
            }
            if (data.dst_uids != null) {
                message.dst_uids = data.dst_uids;
            }
            if (data.message != null) {
                message.message = Message.fromObject(data.message);
            }
            return message;
        }
        toObject() {
            const data: {
                command?: MessageCommand;
                event_uid?: string;
                sender_uid?: string;
                dst_uids?: string[];
                message?: ReturnType<typeof Message.prototype.toObject>;
            } = {};
            if (this.command != null) {
                data.command = this.command;
            }
            if (this.event_uid != null) {
                data.event_uid = this.event_uid;
            }
            if (this.sender_uid != null) {
                data.sender_uid = this.sender_uid;
            }
            if (this.dst_uids != null) {
                data.dst_uids = this.dst_uids;
            }
            if (this.message != null) {
                data.message = this.message.toObject();
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.command != MessageCommand.MESSAGE_SEND)
                writer.writeEnum(1, this.command);
            if (this.event_uid.length)
                writer.writeString(2, this.event_uid);
            if (this.sender_uid.length)
                writer.writeString(3, this.sender_uid);
            if (this.dst_uids.length)
                writer.writeRepeatedString(4, this.dst_uids);
            if (this.has_message)
                writer.writeMessage(5, this.message, () => this.message.serialize(writer));
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): MessageEvent {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new MessageEvent();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.command = reader.readEnum();
                        break;
                    case 2:
                        message.event_uid = reader.readString();
                        break;
                    case 3:
                        message.sender_uid = reader.readString();
                        break;
                    case 4:
                        pb_1.Message.addToRepeatedField(message, 4, reader.readString());
                        break;
                    case 5:
                        reader.readMessage(message.message, () => message.message = Message.deserialize(reader));
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): MessageEvent {
            return MessageEvent.deserialize(bytes);
        }
    }
    export class TypingEvent extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            sender_uid?: string;
            dst_uids?: string[];
            is_typing?: boolean;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [2], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("sender_uid" in data && data.sender_uid != undefined) {
                    this.sender_uid = data.sender_uid;
                }
                if ("dst_uids" in data && data.dst_uids != undefined) {
                    this.dst_uids = data.dst_uids;
                }
                if ("is_typing" in data && data.is_typing != undefined) {
                    this.is_typing = data.is_typing;
                }
            }
        }
        get sender_uid() {
            return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
        }
        set sender_uid(value: string) {
            pb_1.Message.setField(this, 1, value);
        }
        get dst_uids() {
            return pb_1.Message.getFieldWithDefault(this, 2, []) as string[];
        }
        set dst_uids(value: string[]) {
            pb_1.Message.setField(this, 2, value);
        }
        get is_typing() {
            return pb_1.Message.getFieldWithDefault(this, 3, false) as boolean;
        }
        set is_typing(value: boolean) {
            pb_1.Message.setField(this, 3, value);
        }
        static fromObject(data: {
            sender_uid?: string;
            dst_uids?: string[];
            is_typing?: boolean;
        }): TypingEvent {
            const message = new TypingEvent({});
            if (data.sender_uid != null) {
                message.sender_uid = data.sender_uid;
            }
            if (data.dst_uids != null) {
                message.dst_uids = data.dst_uids;
            }
            if (data.is_typing != null) {
                message.is_typing = data.is_typing;
            }
            return message;
        }
        toObject() {
            const data: {
                sender_uid?: string;
                dst_uids?: string[];
                is_typing?: boolean;
            } = {};
            if (this.sender_uid != null) {
                data.sender_uid = this.sender_uid;
            }
            if (this.dst_uids != null) {
                data.dst_uids = this.dst_uids;
            }
            if (this.is_typing != null) {
                data.is_typing = this.is_typing;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.sender_uid.length)
                writer.writeString(1, this.sender_uid);
            if (this.dst_uids.length)
                writer.writeRepeatedString(2, this.dst_uids);
            if (this.is_typing != false)
                writer.writeBool(3, this.is_typing);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): TypingEvent {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new TypingEvent();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.sender_uid = reader.readString();
                        break;
                    case 2:
                        pb_1.Message.addToRepeatedField(message, 2, reader.readString());
                        break;
                    case 3:
                        message.is_typing = reader.readBool();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): TypingEvent {
            return TypingEvent.deserialize(bytes);
        }
    }
    export class UserStatusEvent extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            user_uid?: string;
            is_online?: boolean;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("user_uid" in data && data.user_uid != undefined) {
                    this.user_uid = data.user_uid;
                }
                if ("is_online" in data && data.is_online != undefined) {
                    this.is_online = data.is_online;
                }
            }
        }
        get user_uid() {
            return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
        }
        set user_uid(value: string) {
            pb_1.Message.setField(this, 1, value);
        }
        get is_online() {
            return pb_1.Message.getFieldWithDefault(this, 2, false) as boolean;
        }
        set is_online(value: boolean) {
            pb_1.Message.setField(this, 2, value);
        }
        static fromObject(data: {
            user_uid?: string;
            is_online?: boolean;
        }): UserStatusEvent {
            const message = new UserStatusEvent({});
            if (data.user_uid != null) {
                message.user_uid = data.user_uid;
            }
            if (data.is_online != null) {
                message.is_online = data.is_online;
            }
            return message;
        }
        toObject() {
            const data: {
                user_uid?: string;
                is_online?: boolean;
            } = {};
            if (this.user_uid != null) {
                data.user_uid = this.user_uid;
            }
            if (this.is_online != null) {
                data.is_online = this.is_online;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.user_uid.length)
                writer.writeString(1, this.user_uid);
            if (this.is_online != false)
                writer.writeBool(2, this.is_online);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): UserStatusEvent {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new UserStatusEvent();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.user_uid = reader.readString();
                        break;
                    case 2:
                        message.is_online = reader.readBool();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): UserStatusEvent {
            return UserStatusEvent.deserialize(bytes);
        }
    }
    export class MessageStatusUpdate extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            message_uid?: string;
            new_status?: MessageStatus;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("message_uid" in data && data.message_uid != undefined) {
                    this.message_uid = data.message_uid;
                }
                if ("new_status" in data && data.new_status != undefined) {
                    this.new_status = data.new_status;
                }
            }
        }
        get message_uid() {
            return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
        }
        set message_uid(value: string) {
            pb_1.Message.setField(this, 1, value);
        }
        get new_status() {
            return pb_1.Message.getFieldWithDefault(this, 2, MessageStatus.PENDING) as MessageStatus;
        }
        set new_status(value: MessageStatus) {
            pb_1.Message.setField(this, 2, value);
        }
        static fromObject(data: {
            message_uid?: string;
            new_status?: MessageStatus;
        }): MessageStatusUpdate {
            const message = new MessageStatusUpdate({});
            if (data.message_uid != null) {
                message.message_uid = data.message_uid;
            }
            if (data.new_status != null) {
                message.new_status = data.new_status;
            }
            return message;
        }
        toObject() {
            const data: {
                message_uid?: string;
                new_status?: MessageStatus;
            } = {};
            if (this.message_uid != null) {
                data.message_uid = this.message_uid;
            }
            if (this.new_status != null) {
                data.new_status = this.new_status;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.message_uid.length)
                writer.writeString(1, this.message_uid);
            if (this.new_status != MessageStatus.PENDING)
                writer.writeEnum(2, this.new_status);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): MessageStatusUpdate {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new MessageStatusUpdate();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.message_uid = reader.readString();
                        break;
                    case 2:
                        message.new_status = reader.readEnum();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): MessageStatusUpdate {
            return MessageStatusUpdate.deserialize(bytes);
        }
    }
    export class KeyExchange extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            sender_uid?: string;
            identity_key?: Uint8Array;
            signed_pre_key?: Uint8Array;
            signed_pre_key_signature?: Uint8Array;
            one_time_pre_key?: Uint8Array;
            one_time_pre_key_signature?: Uint8Array;
            ephemeral_key?: Uint8Array;
            encrypted_data?: Uint8Array;
            signature?: string;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("sender_uid" in data && data.sender_uid != undefined) {
                    this.sender_uid = data.sender_uid;
                }
                if ("identity_key" in data && data.identity_key != undefined) {
                    this.identity_key = data.identity_key;
                }
                if ("signed_pre_key" in data && data.signed_pre_key != undefined) {
                    this.signed_pre_key = data.signed_pre_key;
                }
                if ("signed_pre_key_signature" in data && data.signed_pre_key_signature != undefined) {
                    this.signed_pre_key_signature = data.signed_pre_key_signature;
                }
                if ("one_time_pre_key" in data && data.one_time_pre_key != undefined) {
                    this.one_time_pre_key = data.one_time_pre_key;
                }
                if ("one_time_pre_key_signature" in data && data.one_time_pre_key_signature != undefined) {
                    this.one_time_pre_key_signature = data.one_time_pre_key_signature;
                }
                if ("ephemeral_key" in data && data.ephemeral_key != undefined) {
                    this.ephemeral_key = data.ephemeral_key;
                }
                if ("encrypted_data" in data && data.encrypted_data != undefined) {
                    this.encrypted_data = data.encrypted_data;
                }
                if ("signature" in data && data.signature != undefined) {
                    this.signature = data.signature;
                }
            }
        }
        get sender_uid() {
            return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
        }
        set sender_uid(value: string) {
            pb_1.Message.setField(this, 1, value);
        }
        get identity_key() {
            return pb_1.Message.getFieldWithDefault(this, 2, new Uint8Array(0)) as Uint8Array;
        }
        set identity_key(value: Uint8Array) {
            pb_1.Message.setField(this, 2, value);
        }
        get signed_pre_key() {
            return pb_1.Message.getFieldWithDefault(this, 3, new Uint8Array(0)) as Uint8Array;
        }
        set signed_pre_key(value: Uint8Array) {
            pb_1.Message.setField(this, 3, value);
        }
        get signed_pre_key_signature() {
            return pb_1.Message.getFieldWithDefault(this, 4, new Uint8Array(0)) as Uint8Array;
        }
        set signed_pre_key_signature(value: Uint8Array) {
            pb_1.Message.setField(this, 4, value);
        }
        get one_time_pre_key() {
            return pb_1.Message.getFieldWithDefault(this, 5, new Uint8Array(0)) as Uint8Array;
        }
        set one_time_pre_key(value: Uint8Array) {
            pb_1.Message.setField(this, 5, value);
        }
        get one_time_pre_key_signature() {
            return pb_1.Message.getFieldWithDefault(this, 6, new Uint8Array(0)) as Uint8Array;
        }
        set one_time_pre_key_signature(value: Uint8Array) {
            pb_1.Message.setField(this, 6, value);
        }
        get ephemeral_key() {
            return pb_1.Message.getFieldWithDefault(this, 7, new Uint8Array(0)) as Uint8Array;
        }
        set ephemeral_key(value: Uint8Array) {
            pb_1.Message.setField(this, 7, value);
        }
        get encrypted_data() {
            return pb_1.Message.getFieldWithDefault(this, 8, new Uint8Array(0)) as Uint8Array;
        }
        set encrypted_data(value: Uint8Array) {
            pb_1.Message.setField(this, 8, value);
        }
        get signature() {
            return pb_1.Message.getFieldWithDefault(this, 9, "") as string;
        }
        set signature(value: string) {
            pb_1.Message.setField(this, 9, value);
        }
        static fromObject(data: {
            sender_uid?: string;
            identity_key?: Uint8Array;
            signed_pre_key?: Uint8Array;
            signed_pre_key_signature?: Uint8Array;
            one_time_pre_key?: Uint8Array;
            one_time_pre_key_signature?: Uint8Array;
            ephemeral_key?: Uint8Array;
            encrypted_data?: Uint8Array;
            signature?: string;
        }): KeyExchange {
            const message = new KeyExchange({});
            if (data.sender_uid != null) {
                message.sender_uid = data.sender_uid;
            }
            if (data.identity_key != null) {
                message.identity_key = data.identity_key;
            }
            if (data.signed_pre_key != null) {
                message.signed_pre_key = data.signed_pre_key;
            }
            if (data.signed_pre_key_signature != null) {
                message.signed_pre_key_signature = data.signed_pre_key_signature;
            }
            if (data.one_time_pre_key != null) {
                message.one_time_pre_key = data.one_time_pre_key;
            }
            if (data.one_time_pre_key_signature != null) {
                message.one_time_pre_key_signature = data.one_time_pre_key_signature;
            }
            if (data.ephemeral_key != null) {
                message.ephemeral_key = data.ephemeral_key;
            }
            if (data.encrypted_data != null) {
                message.encrypted_data = data.encrypted_data;
            }
            if (data.signature != null) {
                message.signature = data.signature;
            }
            return message;
        }
        toObject() {
            const data: {
                sender_uid?: string;
                identity_key?: Uint8Array;
                signed_pre_key?: Uint8Array;
                signed_pre_key_signature?: Uint8Array;
                one_time_pre_key?: Uint8Array;
                one_time_pre_key_signature?: Uint8Array;
                ephemeral_key?: Uint8Array;
                encrypted_data?: Uint8Array;
                signature?: string;
            } = {};
            if (this.sender_uid != null) {
                data.sender_uid = this.sender_uid;
            }
            if (this.identity_key != null) {
                data.identity_key = this.identity_key;
            }
            if (this.signed_pre_key != null) {
                data.signed_pre_key = this.signed_pre_key;
            }
            if (this.signed_pre_key_signature != null) {
                data.signed_pre_key_signature = this.signed_pre_key_signature;
            }
            if (this.one_time_pre_key != null) {
                data.one_time_pre_key = this.one_time_pre_key;
            }
            if (this.one_time_pre_key_signature != null) {
                data.one_time_pre_key_signature = this.one_time_pre_key_signature;
            }
            if (this.ephemeral_key != null) {
                data.ephemeral_key = this.ephemeral_key;
            }
            if (this.encrypted_data != null) {
                data.encrypted_data = this.encrypted_data;
            }
            if (this.signature != null) {
                data.signature = this.signature;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.sender_uid.length)
                writer.writeString(1, this.sender_uid);
            if (this.identity_key.length)
                writer.writeBytes(2, this.identity_key);
            if (this.signed_pre_key.length)
                writer.writeBytes(3, this.signed_pre_key);
            if (this.signed_pre_key_signature.length)
                writer.writeBytes(4, this.signed_pre_key_signature);
            if (this.one_time_pre_key.length)
                writer.writeBytes(5, this.one_time_pre_key);
            if (this.one_time_pre_key_signature.length)
                writer.writeBytes(6, this.one_time_pre_key_signature);
            if (this.ephemeral_key.length)
                writer.writeBytes(7, this.ephemeral_key);
            if (this.encrypted_data.length)
                writer.writeBytes(8, this.encrypted_data);
            if (this.signature.length)
                writer.writeString(9, this.signature);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): KeyExchange {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new KeyExchange();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.sender_uid = reader.readString();
                        break;
                    case 2:
                        message.identity_key = reader.readBytes();
                        break;
                    case 3:
                        message.signed_pre_key = reader.readBytes();
                        break;
                    case 4:
                        message.signed_pre_key_signature = reader.readBytes();
                        break;
                    case 5:
                        message.one_time_pre_key = reader.readBytes();
                        break;
                    case 6:
                        message.one_time_pre_key_signature = reader.readBytes();
                        break;
                    case 7:
                        message.ephemeral_key = reader.readBytes();
                        break;
                    case 8:
                        message.encrypted_data = reader.readBytes();
                        break;
                    case 9:
                        message.signature = reader.readString();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): KeyExchange {
            return KeyExchange.deserialize(bytes);
        }
    }
    export class SuccessEvent extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            event_uid?: string;
            success_code?: SuccessCode;
            description?: string;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("event_uid" in data && data.event_uid != undefined) {
                    this.event_uid = data.event_uid;
                }
                if ("success_code" in data && data.success_code != undefined) {
                    this.success_code = data.success_code;
                }
                if ("description" in data && data.description != undefined) {
                    this.description = data.description;
                }
            }
        }
        get event_uid() {
            return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
        }
        set event_uid(value: string) {
            pb_1.Message.setField(this, 1, value);
        }
        get success_code() {
            return pb_1.Message.getFieldWithDefault(this, 2, SuccessCode.SUCCESS_UNKNOWN) as SuccessCode;
        }
        set success_code(value: SuccessCode) {
            pb_1.Message.setField(this, 2, value);
        }
        get description() {
            return pb_1.Message.getFieldWithDefault(this, 3, "") as string;
        }
        set description(value: string) {
            pb_1.Message.setField(this, 3, value);
        }
        static fromObject(data: {
            event_uid?: string;
            success_code?: SuccessCode;
            description?: string;
        }): SuccessEvent {
            const message = new SuccessEvent({});
            if (data.event_uid != null) {
                message.event_uid = data.event_uid;
            }
            if (data.success_code != null) {
                message.success_code = data.success_code;
            }
            if (data.description != null) {
                message.description = data.description;
            }
            return message;
        }
        toObject() {
            const data: {
                event_uid?: string;
                success_code?: SuccessCode;
                description?: string;
            } = {};
            if (this.event_uid != null) {
                data.event_uid = this.event_uid;
            }
            if (this.success_code != null) {
                data.success_code = this.success_code;
            }
            if (this.description != null) {
                data.description = this.description;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.event_uid.length)
                writer.writeString(1, this.event_uid);
            if (this.success_code != SuccessCode.SUCCESS_UNKNOWN)
                writer.writeEnum(2, this.success_code);
            if (this.description.length)
                writer.writeString(3, this.description);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): SuccessEvent {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new SuccessEvent();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.event_uid = reader.readString();
                        break;
                    case 2:
                        message.success_code = reader.readEnum();
                        break;
                    case 3:
                        message.description = reader.readString();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): SuccessEvent {
            return SuccessEvent.deserialize(bytes);
        }
    }
    export class Events extends pb_1.Message {
        #one_of_decls: number[][] = [[1, 2, 3, 4, 5, 6]];
        constructor(data?: any[] | ({} & (({
            message_event?: MessageEvent;
            typing_event?: never;
            user_status_event?: never;
            status_update?: never;
            key_exchange_event?: never;
            success_event?: never;
        } | {
            message_event?: never;
            typing_event?: TypingEvent;
            user_status_event?: never;
            status_update?: never;
            key_exchange_event?: never;
            success_event?: never;
        } | {
            message_event?: never;
            typing_event?: never;
            user_status_event?: UserStatusEvent;
            status_update?: never;
            key_exchange_event?: never;
            success_event?: never;
        } | {
            message_event?: never;
            typing_event?: never;
            user_status_event?: never;
            status_update?: MessageStatusUpdate;
            key_exchange_event?: never;
            success_event?: never;
        } | {
            message_event?: never;
            typing_event?: never;
            user_status_event?: never;
            status_update?: never;
            key_exchange_event?: KeyExchange;
            success_event?: never;
        } | {
            message_event?: never;
            typing_event?: never;
            user_status_event?: never;
            status_update?: never;
            key_exchange_event?: never;
            success_event?: SuccessEvent;
        })))) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("message_event" in data && data.message_event != undefined) {
                    this.message_event = data.message_event;
                }
                if ("typing_event" in data && data.typing_event != undefined) {
                    this.typing_event = data.typing_event;
                }
                if ("user_status_event" in data && data.user_status_event != undefined) {
                    this.user_status_event = data.user_status_event;
                }
                if ("status_update" in data && data.status_update != undefined) {
                    this.status_update = data.status_update;
                }
                if ("key_exchange_event" in data && data.key_exchange_event != undefined) {
                    this.key_exchange_event = data.key_exchange_event;
                }
                if ("success_event" in data && data.success_event != undefined) {
                    this.success_event = data.success_event;
                }
            }
        }
        get message_event() {
            return pb_1.Message.getWrapperField(this, MessageEvent, 1) as MessageEvent;
        }
        set message_event(value: MessageEvent) {
            pb_1.Message.setOneofWrapperField(this, 1, this.#one_of_decls[0], value);
        }
        get has_message_event() {
            return pb_1.Message.getField(this, 1) != null;
        }
        get typing_event() {
            return pb_1.Message.getWrapperField(this, TypingEvent, 2) as TypingEvent;
        }
        set typing_event(value: TypingEvent) {
            pb_1.Message.setOneofWrapperField(this, 2, this.#one_of_decls[0], value);
        }
        get has_typing_event() {
            return pb_1.Message.getField(this, 2) != null;
        }
        get user_status_event() {
            return pb_1.Message.getWrapperField(this, UserStatusEvent, 3) as UserStatusEvent;
        }
        set user_status_event(value: UserStatusEvent) {
            pb_1.Message.setOneofWrapperField(this, 3, this.#one_of_decls[0], value);
        }
        get has_user_status_event() {
            return pb_1.Message.getField(this, 3) != null;
        }
        get status_update() {
            return pb_1.Message.getWrapperField(this, MessageStatusUpdate, 4) as MessageStatusUpdate;
        }
        set status_update(value: MessageStatusUpdate) {
            pb_1.Message.setOneofWrapperField(this, 4, this.#one_of_decls[0], value);
        }
        get has_status_update() {
            return pb_1.Message.getField(this, 4) != null;
        }
        get key_exchange_event() {
            return pb_1.Message.getWrapperField(this, KeyExchange, 5) as KeyExchange;
        }
        set key_exchange_event(value: KeyExchange) {
            pb_1.Message.setOneofWrapperField(this, 5, this.#one_of_decls[0], value);
        }
        get has_key_exchange_event() {
            return pb_1.Message.getField(this, 5) != null;
        }
        get success_event() {
            return pb_1.Message.getWrapperField(this, SuccessEvent, 6) as SuccessEvent;
        }
        set success_event(value: SuccessEvent) {
            pb_1.Message.setOneofWrapperField(this, 6, this.#one_of_decls[0], value);
        }
        get has_success_event() {
            return pb_1.Message.getField(this, 6) != null;
        }
        get event() {
            const cases: {
                [index: number]: "none" | "message_event" | "typing_event" | "user_status_event" | "status_update" | "key_exchange_event" | "success_event";
            } = {
                0: "none",
                1: "message_event",
                2: "typing_event",
                3: "user_status_event",
                4: "status_update",
                5: "key_exchange_event",
                6: "success_event"
            };
            return cases[pb_1.Message.computeOneofCase(this, [1, 2, 3, 4, 5, 6])];
        }
        static fromObject(data: {
            message_event?: ReturnType<typeof MessageEvent.prototype.toObject>;
            typing_event?: ReturnType<typeof TypingEvent.prototype.toObject>;
            user_status_event?: ReturnType<typeof UserStatusEvent.prototype.toObject>;
            status_update?: ReturnType<typeof MessageStatusUpdate.prototype.toObject>;
            key_exchange_event?: ReturnType<typeof KeyExchange.prototype.toObject>;
            success_event?: ReturnType<typeof SuccessEvent.prototype.toObject>;
        }): Events {
            const message = new Events({});
            if (data.message_event != null) {
                message.message_event = MessageEvent.fromObject(data.message_event);
            }
            if (data.typing_event != null) {
                message.typing_event = TypingEvent.fromObject(data.typing_event);
            }
            if (data.user_status_event != null) {
                message.user_status_event = UserStatusEvent.fromObject(data.user_status_event);
            }
            if (data.status_update != null) {
                message.status_update = MessageStatusUpdate.fromObject(data.status_update);
            }
            if (data.key_exchange_event != null) {
                message.key_exchange_event = KeyExchange.fromObject(data.key_exchange_event);
            }
            if (data.success_event != null) {
                message.success_event = SuccessEvent.fromObject(data.success_event);
            }
            return message;
        }
        toObject() {
            const data: {
                message_event?: ReturnType<typeof MessageEvent.prototype.toObject>;
                typing_event?: ReturnType<typeof TypingEvent.prototype.toObject>;
                user_status_event?: ReturnType<typeof UserStatusEvent.prototype.toObject>;
                status_update?: ReturnType<typeof MessageStatusUpdate.prototype.toObject>;
                key_exchange_event?: ReturnType<typeof KeyExchange.prototype.toObject>;
                success_event?: ReturnType<typeof SuccessEvent.prototype.toObject>;
            } = {};
            if (this.message_event != null) {
                data.message_event = this.message_event.toObject();
            }
            if (this.typing_event != null) {
                data.typing_event = this.typing_event.toObject();
            }
            if (this.user_status_event != null) {
                data.user_status_event = this.user_status_event.toObject();
            }
            if (this.status_update != null) {
                data.status_update = this.status_update.toObject();
            }
            if (this.key_exchange_event != null) {
                data.key_exchange_event = this.key_exchange_event.toObject();
            }
            if (this.success_event != null) {
                data.success_event = this.success_event.toObject();
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.has_message_event)
                writer.writeMessage(1, this.message_event, () => this.message_event.serialize(writer));
            if (this.has_typing_event)
                writer.writeMessage(2, this.typing_event, () => this.typing_event.serialize(writer));
            if (this.has_user_status_event)
                writer.writeMessage(3, this.user_status_event, () => this.user_status_event.serialize(writer));
            if (this.has_status_update)
                writer.writeMessage(4, this.status_update, () => this.status_update.serialize(writer));
            if (this.has_key_exchange_event)
                writer.writeMessage(5, this.key_exchange_event, () => this.key_exchange_event.serialize(writer));
            if (this.has_success_event)
                writer.writeMessage(6, this.success_event, () => this.success_event.serialize(writer));
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): Events {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new Events();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        reader.readMessage(message.message_event, () => message.message_event = MessageEvent.deserialize(reader));
                        break;
                    case 2:
                        reader.readMessage(message.typing_event, () => message.typing_event = TypingEvent.deserialize(reader));
                        break;
                    case 3:
                        reader.readMessage(message.user_status_event, () => message.user_status_event = UserStatusEvent.deserialize(reader));
                        break;
                    case 4:
                        reader.readMessage(message.status_update, () => message.status_update = MessageStatusUpdate.deserialize(reader));
                        break;
                    case 5:
                        reader.readMessage(message.key_exchange_event, () => message.key_exchange_event = KeyExchange.deserialize(reader));
                        break;
                    case 6:
                        reader.readMessage(message.success_event, () => message.success_event = SuccessEvent.deserialize(reader));
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): Events {
            return Events.deserialize(bytes);
        }
    }
    interface GrpcUnaryServiceInterface<P, R> {
        (message: P, metadata: grpc_1.Metadata, options: grpc_1.CallOptions, callback: grpc_1.requestCallback<R>): grpc_1.ClientUnaryCall;
        (message: P, metadata: grpc_1.Metadata, callback: grpc_1.requestCallback<R>): grpc_1.ClientUnaryCall;
        (message: P, options: grpc_1.CallOptions, callback: grpc_1.requestCallback<R>): grpc_1.ClientUnaryCall;
        (message: P, callback: grpc_1.requestCallback<R>): grpc_1.ClientUnaryCall;
    }
    interface GrpcStreamServiceInterface<P, R> {
        (message: P, metadata: grpc_1.Metadata, options?: grpc_1.CallOptions): grpc_1.ClientReadableStream<R>;
        (message: P, options?: grpc_1.CallOptions): grpc_1.ClientReadableStream<R>;
    }
    interface GrpWritableServiceInterface<P, R> {
        (metadata: grpc_1.Metadata, options: grpc_1.CallOptions, callback: grpc_1.requestCallback<R>): grpc_1.ClientWritableStream<P>;
        (metadata: grpc_1.Metadata, callback: grpc_1.requestCallback<R>): grpc_1.ClientWritableStream<P>;
        (options: grpc_1.CallOptions, callback: grpc_1.requestCallback<R>): grpc_1.ClientWritableStream<P>;
        (callback: grpc_1.requestCallback<R>): grpc_1.ClientWritableStream<P>;
    }
    interface GrpcChunkServiceInterface<P, R> {
        (metadata: grpc_1.Metadata, options?: grpc_1.CallOptions): grpc_1.ClientDuplexStream<P, R>;
        (options?: grpc_1.CallOptions): grpc_1.ClientDuplexStream<P, R>;
    }
    interface GrpcPromiseServiceInterface<P, R> {
        (message: P, metadata: grpc_1.Metadata, options?: grpc_1.CallOptions): Promise<R>;
        (message: P, options?: grpc_1.CallOptions): Promise<R>;
    }
    export abstract class UnimplementedChatService {
        static definition = {
            MessageService: {
                path: "/events.Chat/MessageService",
                requestStream: true,
                responseStream: true,
                requestSerialize: (message: Events) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => Events.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: Events) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => Events.deserialize(new Uint8Array(bytes))
            }
        };
        [method: string]: grpc_1.UntypedHandleCall;
        abstract MessageService(call: grpc_1.ServerDuplexStream<Events, Events>): void;
    }
    export class ChatClient extends grpc_1.makeGenericClientConstructor(UnimplementedChatService.definition, "Chat", {}) {
        constructor(address: string, credentials: grpc_1.ChannelCredentials, options?: Partial<grpc_1.ChannelOptions>) {
            super(address, credentials, options);
        }
        MessageService: GrpcChunkServiceInterface<Events, Events> = (metadata?: grpc_1.Metadata | grpc_1.CallOptions, options?: grpc_1.CallOptions): grpc_1.ClientDuplexStream<Events, Events> => {
            return super.MessageService(metadata, options);
        };
    }
}
