/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 5.29.3
 * source: onboarding.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as pb_1 from "google-protobuf";
import * as grpc_1 from "@grpc/grpc-js";
export namespace onboarding {
    export enum Status {
        OK = 0,
        ERROR = 1,
        INVALID_INPUT = 2,
        INTERNAL_ERROR = 3
    }
    export class PatientOnboardingRequest extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            user_id?: string;
            date_of_birth?: string;
            emergency_contact_name?: string;
            emergency_contact_phone?: string;
            medical_conditions?: string;
            current_medications?: string;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("user_id" in data && data.user_id != undefined) {
                    this.user_id = data.user_id;
                }
                if ("date_of_birth" in data && data.date_of_birth != undefined) {
                    this.date_of_birth = data.date_of_birth;
                }
                if ("emergency_contact_name" in data && data.emergency_contact_name != undefined) {
                    this.emergency_contact_name = data.emergency_contact_name;
                }
                if ("emergency_contact_phone" in data && data.emergency_contact_phone != undefined) {
                    this.emergency_contact_phone = data.emergency_contact_phone;
                }
                if ("medical_conditions" in data && data.medical_conditions != undefined) {
                    this.medical_conditions = data.medical_conditions;
                }
                if ("current_medications" in data && data.current_medications != undefined) {
                    this.current_medications = data.current_medications;
                }
            }
        }
        get user_id() {
            return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
        }
        set user_id(value: string) {
            pb_1.Message.setField(this, 1, value);
        }
        get date_of_birth() {
            return pb_1.Message.getFieldWithDefault(this, 2, "") as string;
        }
        set date_of_birth(value: string) {
            pb_1.Message.setField(this, 2, value);
        }
        get emergency_contact_name() {
            return pb_1.Message.getFieldWithDefault(this, 3, "") as string;
        }
        set emergency_contact_name(value: string) {
            pb_1.Message.setField(this, 3, value);
        }
        get emergency_contact_phone() {
            return pb_1.Message.getFieldWithDefault(this, 4, "") as string;
        }
        set emergency_contact_phone(value: string) {
            pb_1.Message.setField(this, 4, value);
        }
        get medical_conditions() {
            return pb_1.Message.getFieldWithDefault(this, 5, "") as string;
        }
        set medical_conditions(value: string) {
            pb_1.Message.setField(this, 5, value);
        }
        get current_medications() {
            return pb_1.Message.getFieldWithDefault(this, 6, "") as string;
        }
        set current_medications(value: string) {
            pb_1.Message.setField(this, 6, value);
        }
        static fromObject(data: {
            user_id?: string;
            date_of_birth?: string;
            emergency_contact_name?: string;
            emergency_contact_phone?: string;
            medical_conditions?: string;
            current_medications?: string;
        }): PatientOnboardingRequest {
            const message = new PatientOnboardingRequest({});
            if (data.user_id != null) {
                message.user_id = data.user_id;
            }
            if (data.date_of_birth != null) {
                message.date_of_birth = data.date_of_birth;
            }
            if (data.emergency_contact_name != null) {
                message.emergency_contact_name = data.emergency_contact_name;
            }
            if (data.emergency_contact_phone != null) {
                message.emergency_contact_phone = data.emergency_contact_phone;
            }
            if (data.medical_conditions != null) {
                message.medical_conditions = data.medical_conditions;
            }
            if (data.current_medications != null) {
                message.current_medications = data.current_medications;
            }
            return message;
        }
        toObject() {
            const data: {
                user_id?: string;
                date_of_birth?: string;
                emergency_contact_name?: string;
                emergency_contact_phone?: string;
                medical_conditions?: string;
                current_medications?: string;
            } = {};
            if (this.user_id != null) {
                data.user_id = this.user_id;
            }
            if (this.date_of_birth != null) {
                data.date_of_birth = this.date_of_birth;
            }
            if (this.emergency_contact_name != null) {
                data.emergency_contact_name = this.emergency_contact_name;
            }
            if (this.emergency_contact_phone != null) {
                data.emergency_contact_phone = this.emergency_contact_phone;
            }
            if (this.medical_conditions != null) {
                data.medical_conditions = this.medical_conditions;
            }
            if (this.current_medications != null) {
                data.current_medications = this.current_medications;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.user_id.length)
                writer.writeString(1, this.user_id);
            if (this.date_of_birth.length)
                writer.writeString(2, this.date_of_birth);
            if (this.emergency_contact_name.length)
                writer.writeString(3, this.emergency_contact_name);
            if (this.emergency_contact_phone.length)
                writer.writeString(4, this.emergency_contact_phone);
            if (this.medical_conditions.length)
                writer.writeString(5, this.medical_conditions);
            if (this.current_medications.length)
                writer.writeString(6, this.current_medications);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): PatientOnboardingRequest {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new PatientOnboardingRequest();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.user_id = reader.readString();
                        break;
                    case 2:
                        message.date_of_birth = reader.readString();
                        break;
                    case 3:
                        message.emergency_contact_name = reader.readString();
                        break;
                    case 4:
                        message.emergency_contact_phone = reader.readString();
                        break;
                    case 5:
                        message.medical_conditions = reader.readString();
                        break;
                    case 6:
                        message.current_medications = reader.readString();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): PatientOnboardingRequest {
            return PatientOnboardingRequest.deserialize(bytes);
        }
    }
    export class DoctorOnboardingRequest extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            user_id?: string;
            medical_license?: string;
            specialization?: string;
            years_of_experience?: number;
            hospital_affiliation?: string;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("user_id" in data && data.user_id != undefined) {
                    this.user_id = data.user_id;
                }
                if ("medical_license" in data && data.medical_license != undefined) {
                    this.medical_license = data.medical_license;
                }
                if ("specialization" in data && data.specialization != undefined) {
                    this.specialization = data.specialization;
                }
                if ("years_of_experience" in data && data.years_of_experience != undefined) {
                    this.years_of_experience = data.years_of_experience;
                }
                if ("hospital_affiliation" in data && data.hospital_affiliation != undefined) {
                    this.hospital_affiliation = data.hospital_affiliation;
                }
            }
        }
        get user_id() {
            return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
        }
        set user_id(value: string) {
            pb_1.Message.setField(this, 1, value);
        }
        get medical_license() {
            return pb_1.Message.getFieldWithDefault(this, 2, "") as string;
        }
        set medical_license(value: string) {
            pb_1.Message.setField(this, 2, value);
        }
        get specialization() {
            return pb_1.Message.getFieldWithDefault(this, 3, "") as string;
        }
        set specialization(value: string) {
            pb_1.Message.setField(this, 3, value);
        }
        get years_of_experience() {
            return pb_1.Message.getFieldWithDefault(this, 4, 0) as number;
        }
        set years_of_experience(value: number) {
            pb_1.Message.setField(this, 4, value);
        }
        get hospital_affiliation() {
            return pb_1.Message.getFieldWithDefault(this, 5, "") as string;
        }
        set hospital_affiliation(value: string) {
            pb_1.Message.setField(this, 5, value);
        }
        static fromObject(data: {
            user_id?: string;
            medical_license?: string;
            specialization?: string;
            years_of_experience?: number;
            hospital_affiliation?: string;
        }): DoctorOnboardingRequest {
            const message = new DoctorOnboardingRequest({});
            if (data.user_id != null) {
                message.user_id = data.user_id;
            }
            if (data.medical_license != null) {
                message.medical_license = data.medical_license;
            }
            if (data.specialization != null) {
                message.specialization = data.specialization;
            }
            if (data.years_of_experience != null) {
                message.years_of_experience = data.years_of_experience;
            }
            if (data.hospital_affiliation != null) {
                message.hospital_affiliation = data.hospital_affiliation;
            }
            return message;
        }
        toObject() {
            const data: {
                user_id?: string;
                medical_license?: string;
                specialization?: string;
                years_of_experience?: number;
                hospital_affiliation?: string;
            } = {};
            if (this.user_id != null) {
                data.user_id = this.user_id;
            }
            if (this.medical_license != null) {
                data.medical_license = this.medical_license;
            }
            if (this.specialization != null) {
                data.specialization = this.specialization;
            }
            if (this.years_of_experience != null) {
                data.years_of_experience = this.years_of_experience;
            }
            if (this.hospital_affiliation != null) {
                data.hospital_affiliation = this.hospital_affiliation;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.user_id.length)
                writer.writeString(1, this.user_id);
            if (this.medical_license.length)
                writer.writeString(2, this.medical_license);
            if (this.specialization.length)
                writer.writeString(3, this.specialization);
            if (this.years_of_experience != 0)
                writer.writeInt32(4, this.years_of_experience);
            if (this.hospital_affiliation.length)
                writer.writeString(5, this.hospital_affiliation);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): DoctorOnboardingRequest {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new DoctorOnboardingRequest();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.user_id = reader.readString();
                        break;
                    case 2:
                        message.medical_license = reader.readString();
                        break;
                    case 3:
                        message.specialization = reader.readString();
                        break;
                    case 4:
                        message.years_of_experience = reader.readInt32();
                        break;
                    case 5:
                        message.hospital_affiliation = reader.readString();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): DoctorOnboardingRequest {
            return DoctorOnboardingRequest.deserialize(bytes);
        }
    }
    export class OnboardingRequest extends pb_1.Message {
        #one_of_decls: number[][] = [[1, 2]];
        constructor(data?: any[] | ({} & (({
            patient?: PatientOnboardingRequest;
            doctor?: never;
        } | {
            patient?: never;
            doctor?: DoctorOnboardingRequest;
        })))) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("patient" in data && data.patient != undefined) {
                    this.patient = data.patient;
                }
                if ("doctor" in data && data.doctor != undefined) {
                    this.doctor = data.doctor;
                }
            }
        }
        get patient() {
            return pb_1.Message.getWrapperField(this, PatientOnboardingRequest, 1) as PatientOnboardingRequest;
        }
        set patient(value: PatientOnboardingRequest) {
            pb_1.Message.setOneofWrapperField(this, 1, this.#one_of_decls[0], value);
        }
        get has_patient() {
            return pb_1.Message.getField(this, 1) != null;
        }
        get doctor() {
            return pb_1.Message.getWrapperField(this, DoctorOnboardingRequest, 2) as DoctorOnboardingRequest;
        }
        set doctor(value: DoctorOnboardingRequest) {
            pb_1.Message.setOneofWrapperField(this, 2, this.#one_of_decls[0], value);
        }
        get has_doctor() {
            return pb_1.Message.getField(this, 2) != null;
        }
        get profile() {
            const cases: {
                [index: number]: "none" | "patient" | "doctor";
            } = {
                0: "none",
                1: "patient",
                2: "doctor"
            };
            return cases[pb_1.Message.computeOneofCase(this, [1, 2])];
        }
        static fromObject(data: {
            patient?: ReturnType<typeof PatientOnboardingRequest.prototype.toObject>;
            doctor?: ReturnType<typeof DoctorOnboardingRequest.prototype.toObject>;
        }): OnboardingRequest {
            const message = new OnboardingRequest({});
            if (data.patient != null) {
                message.patient = PatientOnboardingRequest.fromObject(data.patient);
            }
            if (data.doctor != null) {
                message.doctor = DoctorOnboardingRequest.fromObject(data.doctor);
            }
            return message;
        }
        toObject() {
            const data: {
                patient?: ReturnType<typeof PatientOnboardingRequest.prototype.toObject>;
                doctor?: ReturnType<typeof DoctorOnboardingRequest.prototype.toObject>;
            } = {};
            if (this.patient != null) {
                data.patient = this.patient.toObject();
            }
            if (this.doctor != null) {
                data.doctor = this.doctor.toObject();
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.has_patient)
                writer.writeMessage(1, this.patient, () => this.patient.serialize(writer));
            if (this.has_doctor)
                writer.writeMessage(2, this.doctor, () => this.doctor.serialize(writer));
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): OnboardingRequest {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new OnboardingRequest();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        reader.readMessage(message.patient, () => message.patient = PatientOnboardingRequest.deserialize(reader));
                        break;
                    case 2:
                        reader.readMessage(message.doctor, () => message.doctor = DoctorOnboardingRequest.deserialize(reader));
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): OnboardingRequest {
            return OnboardingRequest.deserialize(bytes);
        }
    }
    export class OnboardingResponse extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            status?: Status;
            message?: string;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("status" in data && data.status != undefined) {
                    this.status = data.status;
                }
                if ("message" in data && data.message != undefined) {
                    this.message = data.message;
                }
            }
        }
        get status() {
            return pb_1.Message.getFieldWithDefault(this, 1, Status.OK) as Status;
        }
        set status(value: Status) {
            pb_1.Message.setField(this, 1, value);
        }
        get message() {
            return pb_1.Message.getFieldWithDefault(this, 2, "") as string;
        }
        set message(value: string) {
            pb_1.Message.setField(this, 2, value);
        }
        static fromObject(data: {
            status?: Status;
            message?: string;
        }): OnboardingResponse {
            const message = new OnboardingResponse({});
            if (data.status != null) {
                message.status = data.status;
            }
            if (data.message != null) {
                message.message = data.message;
            }
            return message;
        }
        toObject() {
            const data: {
                status?: Status;
                message?: string;
            } = {};
            if (this.status != null) {
                data.status = this.status;
            }
            if (this.message != null) {
                data.message = this.message;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.status != Status.OK)
                writer.writeEnum(1, this.status);
            if (this.message.length)
                writer.writeString(2, this.message);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): OnboardingResponse {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new OnboardingResponse();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.status = reader.readEnum();
                        break;
                    case 2:
                        message.message = reader.readString();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): OnboardingResponse {
            return OnboardingResponse.deserialize(bytes);
        }
    }
    interface GrpcUnaryServiceInterface<P, R> {
        (message: P, metadata: grpc_1.Metadata, options: grpc_1.CallOptions, callback: grpc_1.requestCallback<R>): grpc_1.ClientUnaryCall;
        (message: P, metadata: grpc_1.Metadata, callback: grpc_1.requestCallback<R>): grpc_1.ClientUnaryCall;
        (message: P, options: grpc_1.CallOptions, callback: grpc_1.requestCallback<R>): grpc_1.ClientUnaryCall;
        (message: P, callback: grpc_1.requestCallback<R>): grpc_1.ClientUnaryCall;
    }
    interface GrpcStreamServiceInterface<P, R> {
        (message: P, metadata: grpc_1.Metadata, options?: grpc_1.CallOptions): grpc_1.ClientReadableStream<R>;
        (message: P, options?: grpc_1.CallOptions): grpc_1.ClientReadableStream<R>;
    }
    interface GrpWritableServiceInterface<P, R> {
        (metadata: grpc_1.Metadata, options: grpc_1.CallOptions, callback: grpc_1.requestCallback<R>): grpc_1.ClientWritableStream<P>;
        (metadata: grpc_1.Metadata, callback: grpc_1.requestCallback<R>): grpc_1.ClientWritableStream<P>;
        (options: grpc_1.CallOptions, callback: grpc_1.requestCallback<R>): grpc_1.ClientWritableStream<P>;
        (callback: grpc_1.requestCallback<R>): grpc_1.ClientWritableStream<P>;
    }
    interface GrpcChunkServiceInterface<P, R> {
        (metadata: grpc_1.Metadata, options?: grpc_1.CallOptions): grpc_1.ClientDuplexStream<P, R>;
        (options?: grpc_1.CallOptions): grpc_1.ClientDuplexStream<P, R>;
    }
    interface GrpcPromiseServiceInterface<P, R> {
        (message: P, metadata: grpc_1.Metadata, options?: grpc_1.CallOptions): Promise<R>;
        (message: P, options?: grpc_1.CallOptions): Promise<R>;
    }
    export abstract class UnimplementedOnboardingService {
        static definition = {
            CompleteOnboarding: {
                path: "/onboarding.Onboarding/CompleteOnboarding",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: OnboardingRequest) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => OnboardingRequest.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: OnboardingResponse) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => OnboardingResponse.deserialize(new Uint8Array(bytes))
            }
        };
        [method: string]: grpc_1.UntypedHandleCall;
        abstract CompleteOnboarding(call: grpc_1.ServerUnaryCall<OnboardingRequest, OnboardingResponse>, callback: grpc_1.sendUnaryData<OnboardingResponse>): void;
    }
    export class OnboardingClient extends grpc_1.makeGenericClientConstructor(UnimplementedOnboardingService.definition, "Onboarding", {}) {
        constructor(address: string, credentials: grpc_1.ChannelCredentials, options?: Partial<grpc_1.ChannelOptions>) {
            super(address, credentials, options);
        }
        CompleteOnboarding: GrpcUnaryServiceInterface<OnboardingRequest, OnboardingResponse> = (message: OnboardingRequest, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<OnboardingResponse>, options?: grpc_1.CallOptions | grpc_1.requestCallback<OnboardingResponse>, callback?: grpc_1.requestCallback<OnboardingResponse>): grpc_1.ClientUnaryCall => {
            return super.CompleteOnboarding(message, metadata, options, callback);
        };
    }
}
